/** Auto-generated by scripts/promote-all-certs-to-associate.mjs */
import type { AssociateSpikeBody } from '../types'
import { validateAssociateSpikeBody } from '../validate-body'
import administratorPracticeTestJson from './administrator-practice-test.json'
import advancedFieldServiceApJson from './advanced-field-service-ap.json'
import agentforceSpecialistJson from './agentforce-specialist.json'
import applicationArchitectJson from './application-architect.json'
import b2bCommerceAdminApJson from './b2b-commerce-admin-ap.json'
import b2bCommerceDeveloperApJson from './b2b-commerce-developer-ap.json'
import b2bSolutionArchitectJson from './b2b-solution-architect.json'
import b2cCommerceArchitectJson from './b2c-commerce-architect.json'
import b2cCommerceDeveloperJson from './b2c-commerce-developer.json'
import b2cSolutionArchitectJson from './b2c-solution-architect.json'
import businessAnalystJson from './business-analyst.json'
import communicationsCloudApJson from './communications-cloud-ap.json'
import consumerGoodsCloudApJson from './consumer-goods-cloud-ap.json'
import consumerGoodsTpmApJson from './consumer-goods-tpm-ap.json'
import contactCenterApJson from './contact-center-ap.json'
import cpqAdministratorJson from './cpq-administrator.json'
import cpqBillingApJson from './cpq-billing-ap.json'
import crmAnalyticsEinsteinDiscoveryConsultantJson from './crm-analytics-einstein-discovery-consultant.json'
import dataArchitectJson from './data-architect.json'
import dataCloudConsultantJson from './data-360-consultant.json'
import devLifecycleDeploymentArchitectJson from './dev-lifecycle-deployment-architect.json'
import developer2Json from './developer-2.json'
import educationCloudConsultantJson from './education-cloud-consultant.json'
import emailSpecialistJson from './email-specialist.json'
import emailSpecialistPracticeTestJson from './email-specialist-practice-test.json'
import energyUtilitiesApJson from './energy-utilities-ap.json'
import experienceCloudJson from './experience-cloud.json'
import fieldServiceJson from './field-service.json'
import financialServicesCloudApJson from './financial-services-cloud-ap.json'
import healthCloudApJson from './health-cloud-ap.json'
import herokuArchitectJson from './heroku-architect.json'
import herokuDeveloperApJson from './heroku-developer-ap.json'
import identityAccessManagementArchitectJson from './identity-access-management-architect.json'
import industriesCpqDeveloperJson from './industries-cpq-developer.json'
import integrationArchitectJson from './integration-architect.json'
import javascriptDeveloperIJson from './javascript-developer-i.json'
import loyaltyManagementApJson from './loyalty-management-ap.json'
import manufacturingCloudApJson from './manufacturing-cloud-ap.json'
import marketingCloudAdvancedCrossChannelApJson from './marketing-cloud-advanced-cross-channel-ap.json'
import marketingCloudConsultantJson from './marketing-cloud-consultant.json'
import marketingCloudEngagementAdminJson from './marketing-cloud-engagement-admin.json'
import marketingCloudEngagementDeveloperJson from './marketing-cloud-engagement-developer.json'
import marketingCloudEngagementFoundationsJson from './marketing-cloud-engagement-foundations.json'
import marketingCloudIntelligenceApJson from './marketing-cloud-intelligence-ap.json'
import marketingCloudPersonalizationApJson from './marketing-cloud-personalization-ap.json'
import mediaCloudApJson from './media-cloud-ap.json'
import mulesoftCatalystConsultantJson from './mulesoft-catalyst-consultant.json'
import mulesoftDeveloperIJson from './mulesoft-developer-i.json'
import mulesoftDeveloperIiJson from './mulesoft-developer-ii.json'
import mulesoftHyperautomationDeveloperJson from './mulesoft-hyperautomation-developer.json'
import mulesoftIntegrationArchitectJson from './mulesoft-integration-architect.json'
import mulesoftIntegrationFoundationsJson from './mulesoft-integration-foundations.json'
import mulesoftPlatformArchitectJson from './mulesoft-platform-architect.json'
import netZeroCloudApJson from './net-zero-cloud-ap.json'
import nonprofitCloudJson from './nonprofit-cloud.json'
import nonprofitSuccessPackConsultantJson from './nonprofit-success-pack-consultant.json'
import omnistudioConsultantJson from './omnistudio-consultant.json'
import omnistudioDeveloperJson from './omnistudio-developer.json'
import orderManagementAdminApJson from './order-management-admin-ap.json'
import orderManagementDeveloperApJson from './order-management-developer-ap.json'
import pardotConsultantJson from './pardot-consultant.json'
import pardotSpecialistJson from './pardot-specialist.json'
import platformFoundationsJson from './platform-foundations.json'
import processAutomationApJson from './process-automation-ap.json'
import publicSectorSolutionsApJson from './public-sector-solutions-ap.json'
import revenueCloudConsultantJson from './revenue-cloud-consultant.json'
import salesCloudJson from './sales-cloud.json'
import salesFoundationsJson from './sales-foundations.json'
import serviceCloudJson from './service-cloud.json'
import sharingVisibilityArchitectJson from './sharing-visibility-architect.json'
import slackAdministratorJson from './slack-administrator.json'
import slackConsultantJson from './slack-consultant.json'
import slackDeveloperJson from './slack-developer.json'
import strategyDesignerJson from './strategy-designer.json'
import systemArchitectJson from './system-architect.json'
import tableauArchitectJson from './tableau-architect.json'
import tableauConsultantJson from './tableau-consultant.json'
import tableauDataAnalystJson from './tableau-data-analyst.json'
import tableauDesktopFoundationsJson from './tableau-desktop-foundations.json'
import tableauServerAdministratorJson from './tableau-server-administrator.json'
import technicalArchitectJson from './technical-architect.json'
import technicalArchitectEvaluationJson from './technical-architect-evaluation.json'
import technicalArchitectReviewBoardJson from './technical-architect-review-board.json'
import uxDesignerJson from './ux-designer.json'
import claudeCertifiedAssociateJson from './claude-certified-associate.json'
import claudeCertifiedDeveloperJson from './claude-certified-developer.json'
import claudeCertifiedArchitectFoundationsJson from './claude-certified-architect-foundations.json'
import claudeCertifiedArchitectProfessionalJson from './claude-certified-architect-professional.json'

// Removed unsafe asBody() in favor of explicit validateAssociateSpikeBody() calls

/** Slugs with JSON bodies (associate template via registry). */
export const PROMOTED_ASSOCIATE_SLUGS = [
  'administrator-practice-test',
  'advanced-field-service-ap',
  'agentforce-specialist',
  'application-architect',
  'b2b-commerce-admin-ap',
  'b2b-commerce-developer-ap',
  'b2b-solution-architect',
  'b2c-commerce-architect',
  'b2c-commerce-developer',
  'b2c-solution-architect',
  'business-analyst',
  'communications-cloud-ap',
  'consumer-goods-cloud-ap',
  'consumer-goods-tpm-ap',
  'contact-center-ap',
  'cpq-administrator',
  'cpq-billing-ap',
  'crm-analytics-einstein-discovery-consultant',
  'data-architect',
  'data-360-consultant',
  'dev-lifecycle-deployment-architect',
  'developer-2',
  'education-cloud-consultant',
  'email-specialist',
  'email-specialist-practice-test',
  'energy-utilities-ap',
  'experience-cloud',
  'field-service',
  'financial-services-cloud-ap',
  'health-cloud-ap',
  'heroku-architect',
  'heroku-developer-ap',
  'identity-access-management-architect',
  'industries-cpq-developer',
  'integration-architect',
  'javascript-developer-i',
  'loyalty-management-ap',
  'manufacturing-cloud-ap',
  'marketing-cloud-advanced-cross-channel-ap',
  'marketing-cloud-consultant',
  'marketing-cloud-engagement-admin',
  'marketing-cloud-engagement-developer',
  'marketing-cloud-engagement-foundations',
  'marketing-cloud-intelligence-ap',
  'marketing-cloud-personalization-ap',
  'media-cloud-ap',
  'mulesoft-catalyst-consultant',
  'mulesoft-developer-i',
  'mulesoft-developer-ii',
  'mulesoft-hyperautomation-developer',
  'mulesoft-integration-architect',
  'mulesoft-integration-foundations',
  'mulesoft-platform-architect',
  'net-zero-cloud-ap',
  'nonprofit-cloud',
  'nonprofit-success-pack-consultant',
  'omnistudio-consultant',
  'omnistudio-developer',
  'order-management-admin-ap',
  'order-management-developer-ap',
  'pardot-consultant',
  'pardot-specialist',
  'platform-foundations',
  'process-automation-ap',
  'public-sector-solutions-ap',
  'revenue-cloud-consultant',
  'sales-cloud',
  'sales-foundations',
  'service-cloud',
  'sharing-visibility-architect',
  'slack-administrator',
  'slack-consultant',
  'slack-developer',
  'strategy-designer',
  'system-architect',
  'tableau-architect',
  'tableau-consultant',
  'tableau-data-analyst',
  'tableau-desktop-foundations',
  'tableau-server-administrator',
  'technical-architect',
  'technical-architect-evaluation',
  'technical-architect-review-board',
  'ux-designer',
  'claude-certified-associate',
  'claude-certified-developer',
  'claude-certified-architect-foundations',
  'claude-certified-architect-professional',
] as const

export type PromotedAssociateSlug = (typeof PROMOTED_ASSOCIATE_SLUGS)[number]

export const promotedAssociateCertBodies: Record<PromotedAssociateSlug, AssociateSpikeBody> = {
  'administrator-practice-test': validateAssociateSpikeBody(administratorPracticeTestJson, 'administrator-practice-test'),
  'advanced-field-service-ap': validateAssociateSpikeBody(advancedFieldServiceApJson, 'advanced-field-service-ap'),
  'agentforce-specialist': validateAssociateSpikeBody(agentforceSpecialistJson, 'agentforce-specialist'),
  'application-architect': validateAssociateSpikeBody(applicationArchitectJson, 'application-architect'),
  'b2b-commerce-admin-ap': validateAssociateSpikeBody(b2bCommerceAdminApJson, 'b2b-commerce-admin-ap'),
  'b2b-commerce-developer-ap': validateAssociateSpikeBody(b2bCommerceDeveloperApJson, 'b2b-commerce-developer-ap'),
  'b2b-solution-architect': validateAssociateSpikeBody(b2bSolutionArchitectJson, 'b2b-solution-architect'),
  'b2c-commerce-architect': validateAssociateSpikeBody(b2cCommerceArchitectJson, 'b2c-commerce-architect'),
  'b2c-commerce-developer': validateAssociateSpikeBody(b2cCommerceDeveloperJson, 'b2c-commerce-developer'),
  'b2c-solution-architect': validateAssociateSpikeBody(b2cSolutionArchitectJson, 'b2c-solution-architect'),
  'business-analyst': validateAssociateSpikeBody(businessAnalystJson, 'business-analyst'),
  'communications-cloud-ap': validateAssociateSpikeBody(communicationsCloudApJson, 'communications-cloud-ap'),
  'consumer-goods-cloud-ap': validateAssociateSpikeBody(consumerGoodsCloudApJson, 'consumer-goods-cloud-ap'),
  'consumer-goods-tpm-ap': validateAssociateSpikeBody(consumerGoodsTpmApJson, 'consumer-goods-tpm-ap'),
  'contact-center-ap': validateAssociateSpikeBody(contactCenterApJson, 'contact-center-ap'),
  'cpq-administrator': validateAssociateSpikeBody(cpqAdministratorJson, 'cpq-administrator'),
  'cpq-billing-ap': validateAssociateSpikeBody(cpqBillingApJson, 'cpq-billing-ap'),
  'crm-analytics-einstein-discovery-consultant': validateAssociateSpikeBody(crmAnalyticsEinsteinDiscoveryConsultantJson, 'crm-analytics-einstein-discovery-consultant'),
  'data-architect': validateAssociateSpikeBody(dataArchitectJson, 'data-architect'),
  'data-360-consultant': validateAssociateSpikeBody(dataCloudConsultantJson, 'data-360-consultant'),
  'dev-lifecycle-deployment-architect': validateAssociateSpikeBody(devLifecycleDeploymentArchitectJson, 'dev-lifecycle-deployment-architect'),
  'developer-2': validateAssociateSpikeBody(developer2Json, 'developer-2'),
  'education-cloud-consultant': validateAssociateSpikeBody(educationCloudConsultantJson, 'education-cloud-consultant'),
  'email-specialist': validateAssociateSpikeBody(emailSpecialistJson, 'email-specialist'),
  'email-specialist-practice-test': validateAssociateSpikeBody(emailSpecialistPracticeTestJson, 'email-specialist-practice-test'),
  'energy-utilities-ap': validateAssociateSpikeBody(energyUtilitiesApJson, 'energy-utilities-ap'),
  'experience-cloud': validateAssociateSpikeBody(experienceCloudJson, 'experience-cloud'),
  'field-service': validateAssociateSpikeBody(fieldServiceJson, 'field-service'),
  'financial-services-cloud-ap': validateAssociateSpikeBody(financialServicesCloudApJson, 'financial-services-cloud-ap'),
  'health-cloud-ap': validateAssociateSpikeBody(healthCloudApJson, 'health-cloud-ap'),
  'heroku-architect': validateAssociateSpikeBody(herokuArchitectJson, 'heroku-architect'),
  'heroku-developer-ap': validateAssociateSpikeBody(herokuDeveloperApJson, 'heroku-developer-ap'),
  'identity-access-management-architect': validateAssociateSpikeBody(identityAccessManagementArchitectJson, 'identity-access-management-architect'),
  'industries-cpq-developer': validateAssociateSpikeBody(industriesCpqDeveloperJson, 'industries-cpq-developer'),
  'integration-architect': validateAssociateSpikeBody(integrationArchitectJson, 'integration-architect'),
  'javascript-developer-i': validateAssociateSpikeBody(javascriptDeveloperIJson, 'javascript-developer-i'),
  'loyalty-management-ap': validateAssociateSpikeBody(loyaltyManagementApJson, 'loyalty-management-ap'),
  'manufacturing-cloud-ap': validateAssociateSpikeBody(manufacturingCloudApJson, 'manufacturing-cloud-ap'),
  'marketing-cloud-advanced-cross-channel-ap': validateAssociateSpikeBody(marketingCloudAdvancedCrossChannelApJson, 'marketing-cloud-advanced-cross-channel-ap'),
  'marketing-cloud-consultant': validateAssociateSpikeBody(marketingCloudConsultantJson, 'marketing-cloud-consultant'),
  'marketing-cloud-engagement-admin': validateAssociateSpikeBody(marketingCloudEngagementAdminJson, 'marketing-cloud-engagement-admin'),
  'marketing-cloud-engagement-developer': validateAssociateSpikeBody(marketingCloudEngagementDeveloperJson, 'marketing-cloud-engagement-developer'),
  'marketing-cloud-engagement-foundations': validateAssociateSpikeBody(marketingCloudEngagementFoundationsJson, 'marketing-cloud-engagement-foundations'),
  'marketing-cloud-intelligence-ap': validateAssociateSpikeBody(marketingCloudIntelligenceApJson, 'marketing-cloud-intelligence-ap'),
  'marketing-cloud-personalization-ap': validateAssociateSpikeBody(marketingCloudPersonalizationApJson, 'marketing-cloud-personalization-ap'),
  'media-cloud-ap': validateAssociateSpikeBody(mediaCloudApJson, 'media-cloud-ap'),
  'mulesoft-catalyst-consultant': validateAssociateSpikeBody(mulesoftCatalystConsultantJson, 'mulesoft-catalyst-consultant'),
  'mulesoft-developer-i': validateAssociateSpikeBody(mulesoftDeveloperIJson, 'mulesoft-developer-i'),
  'mulesoft-developer-ii': validateAssociateSpikeBody(mulesoftDeveloperIiJson, 'mulesoft-developer-ii'),
  'mulesoft-hyperautomation-developer': validateAssociateSpikeBody(mulesoftHyperautomationDeveloperJson, 'mulesoft-hyperautomation-developer'),
  'mulesoft-integration-architect': validateAssociateSpikeBody(mulesoftIntegrationArchitectJson, 'mulesoft-integration-architect'),
  'mulesoft-integration-foundations': validateAssociateSpikeBody(mulesoftIntegrationFoundationsJson, 'mulesoft-integration-foundations'),
  'mulesoft-platform-architect': validateAssociateSpikeBody(mulesoftPlatformArchitectJson, 'mulesoft-platform-architect'),
  'net-zero-cloud-ap': validateAssociateSpikeBody(netZeroCloudApJson, 'net-zero-cloud-ap'),
  'nonprofit-cloud': validateAssociateSpikeBody(nonprofitCloudJson, 'nonprofit-cloud'),
  'nonprofit-success-pack-consultant': validateAssociateSpikeBody(nonprofitSuccessPackConsultantJson, 'nonprofit-success-pack-consultant'),
  'omnistudio-consultant': validateAssociateSpikeBody(omnistudioConsultantJson, 'omnistudio-consultant'),
  'omnistudio-developer': validateAssociateSpikeBody(omnistudioDeveloperJson, 'omnistudio-developer'),
  'order-management-admin-ap': validateAssociateSpikeBody(orderManagementAdminApJson, 'order-management-admin-ap'),
  'order-management-developer-ap': validateAssociateSpikeBody(orderManagementDeveloperApJson, 'order-management-developer-ap'),
  'pardot-consultant': validateAssociateSpikeBody(pardotConsultantJson, 'pardot-consultant'),
  'pardot-specialist': validateAssociateSpikeBody(pardotSpecialistJson, 'pardot-specialist'),
  'platform-foundations': validateAssociateSpikeBody(platformFoundationsJson, 'platform-foundations'),
  'process-automation-ap': validateAssociateSpikeBody(processAutomationApJson, 'process-automation-ap'),
  'public-sector-solutions-ap': validateAssociateSpikeBody(publicSectorSolutionsApJson, 'public-sector-solutions-ap'),
  'revenue-cloud-consultant': validateAssociateSpikeBody(revenueCloudConsultantJson, 'revenue-cloud-consultant'),
  'sales-cloud': validateAssociateSpikeBody(salesCloudJson, 'sales-cloud'),
  'sales-foundations': validateAssociateSpikeBody(salesFoundationsJson, 'sales-foundations'),
  'service-cloud': validateAssociateSpikeBody(serviceCloudJson, 'service-cloud'),
  'sharing-visibility-architect': validateAssociateSpikeBody(sharingVisibilityArchitectJson, 'sharing-visibility-architect'),
  'slack-administrator': validateAssociateSpikeBody(slackAdministratorJson, 'slack-administrator'),
  'slack-consultant': validateAssociateSpikeBody(slackConsultantJson, 'slack-consultant'),
  'slack-developer': validateAssociateSpikeBody(slackDeveloperJson, 'slack-developer'),
  'strategy-designer': validateAssociateSpikeBody(strategyDesignerJson, 'strategy-designer'),
  'system-architect': validateAssociateSpikeBody(systemArchitectJson, 'system-architect'),
  'tableau-architect': validateAssociateSpikeBody(tableauArchitectJson, 'tableau-architect'),
  'tableau-consultant': validateAssociateSpikeBody(tableauConsultantJson, 'tableau-consultant'),
  'tableau-data-analyst': validateAssociateSpikeBody(tableauDataAnalystJson, 'tableau-data-analyst'),
  'tableau-desktop-foundations': validateAssociateSpikeBody(tableauDesktopFoundationsJson, 'tableau-desktop-foundations'),
  'tableau-server-administrator': validateAssociateSpikeBody(tableauServerAdministratorJson, 'tableau-server-administrator'),
  'technical-architect': validateAssociateSpikeBody(technicalArchitectJson, 'technical-architect'),
  'technical-architect-evaluation': validateAssociateSpikeBody(technicalArchitectEvaluationJson, 'technical-architect-evaluation'),
  'technical-architect-review-board': validateAssociateSpikeBody(technicalArchitectReviewBoardJson, 'technical-architect-review-board'),
  'ux-designer': validateAssociateSpikeBody(uxDesignerJson, 'ux-designer'),
  'claude-certified-associate': validateAssociateSpikeBody(claudeCertifiedAssociateJson, 'claude-certified-associate'),
  'claude-certified-developer': validateAssociateSpikeBody(claudeCertifiedDeveloperJson, 'claude-certified-developer'),
  'claude-certified-architect-foundations': validateAssociateSpikeBody(claudeCertifiedArchitectFoundationsJson, 'claude-certified-architect-foundations'),
  'claude-certified-architect-professional': validateAssociateSpikeBody(claudeCertifiedArchitectProfessionalJson, 'claude-certified-architect-professional'),
}
