/**
 * Official "Salesforce Certified" naming for every certification slug.
 * Single source of truth so all pages (titles, H1, meta, breadcrumbs, cards) use consistent naming.
 * For renamed certs with former names, see cert-name-aliases.ts (primaryName overrides here).
 */

export const OFFICIAL_CERT_NAMES: Record<string, string> = {
  // Associate / Foundations
  'platform-foundations': 'Salesforce Certified Platform Foundations',
  'ai-associate': 'Salesforce Certified AI Associate',
  'marketing-cloud-engagement-foundations': 'Salesforce Certified Marketing Cloud Engagement Foundations',
  'mulesoft-integration-foundations': 'Salesforce Certified MuleSoft Integration Foundations',
  // Administrator (aliases in cert-name-aliases)
  administrator: 'Salesforce Certified Platform Administrator',
  'advanced-administrator': 'Salesforce Certified Platform Administrator II',
  'app-builder': 'Salesforce Certified Platform App Builder',
  'agentforce-specialist': 'Salesforce Certified Agentforce Specialist',
  'business-analyst': 'Salesforce Certified Business Analyst',
  'cpq-administrator': 'Salesforce Certified CPQ Administrator',
  'marketing-cloud-engagement-admin': 'Salesforce Certified Marketing Cloud Engagement Administrator',
  'slack-administrator': 'Salesforce Certified Slack Administrator',
  'administrator-practice-test': 'Salesforce Certified Platform Administrator Practice Test',
  // Developer
  'developer-1': 'Salesforce Certified Platform Developer',
  'developer-2': 'Salesforce Certified Platform Developer II',
  'javascript-developer-i': 'Salesforce Certified JavaScript Developer',
  'b2c-commerce-developer': 'Salesforce Certified B2C Commerce Cloud Developer',
  'industries-cpq-developer': 'Salesforce Certified Industries CPQ Developer',
  'marketing-cloud-engagement-developer': 'Salesforce Certified Marketing Cloud Engagement Developer',
  'mulesoft-developer-i': 'Salesforce Certified MuleSoft Developer',
  'mulesoft-developer-ii': 'Salesforce Certified MuleSoft Developer II',
  'mulesoft-hyperautomation-developer': 'Salesforce Certified MuleSoft Hyperautomation Developer',
  'omnistudio-developer': 'Salesforce Certified OmniStudio Developer',
  'slack-developer': 'Salesforce Certified Slack Developer',
  // Consultant
  'crm-analytics-einstein-discovery-consultant': 'Salesforce Certified CRM Analytics & Einstein Discovery Consultant',
  'data-360-consultant': 'Salesforce Certified Data Cloud Consultant',
  'education-cloud-consultant': 'Salesforce Certified Education Cloud Consultant',
  'experience-cloud': 'Salesforce Certified Experience Cloud Consultant',
  'field-service': 'Salesforce Certified Agentforce Field Service and Operations Consultant',
  'pardot-consultant': 'Salesforce Certified Account Engagement (Pardot) Consultant',
  'marketing-cloud-consultant': 'Salesforce Certified Marketing Cloud Engagement Consultant',
  'nonprofit-cloud': 'Salesforce Certified Agentforce Nonprofit Consultant',
  'nonprofit-success-pack-consultant': 'Salesforce Certified Nonprofit Success Pack (NPSP) Consultant',
  'omnistudio-consultant': 'Salesforce Certified OmniStudio Consultant',
  'revenue-cloud-consultant': 'Salesforce Certified Revenue Management Consultant',
  'sales-cloud': 'Salesforce Certified Agentforce Sales Consultant',
  'service-cloud': 'Salesforce Certified Agentforce Service Consultant',
  'slack-consultant': 'Salesforce Certified Slack Consultant',
  // Marketing
  'email-specialist': 'Salesforce Certified Marketing Cloud Engagement Specialist',
  'pardot-specialist': 'Salesforce Certified Account Engagement (Pardot) Specialist',
  'email-specialist-practice-test': 'Salesforce Certified Marketing Cloud Engagement Specialist Practice Test',
  // Architect
  'application-architect': 'Salesforce Certified Application Architect',
  'data-architect': 'Salesforce Certified Platform Data Architect',
  'integration-architect': 'Salesforce Certified Platform Integration Architect',
  'sharing-visibility-architect': 'Salesforce Certified Platform Sharing and Visibility Architect',
  'system-architect': 'Salesforce Certified System Architect',
  'identity-access-management-architect': 'Salesforce Certified Platform Identity and Access Management Architect',
  'dev-lifecycle-deployment-architect': 'Salesforce Certified Platform Development Lifecycle and Deployment Architect',
  'technical-architect': 'Salesforce Certified Technical Architect (CTA)',
  'technical-architect-evaluation': 'Salesforce Certified Technical Architect - Architect Evaluation',
  'technical-architect-review-board': 'Salesforce Certified Technical Architect - Architect Review Board',
  'b2b-solution-architect': 'Salesforce Certified B2B Solution Architect',
  'b2c-commerce-architect': 'Salesforce Certified B2C Commerce Architect',
  'b2c-solution-architect': 'Salesforce Certified B2C Solution Architect',
  'heroku-architect': 'Salesforce Certified Heroku Architect',
  'mulesoft-catalyst-consultant': 'Salesforce Certified MuleSoft Catalyst Consultant',
  'mulesoft-platform-architect': 'Salesforce Certified MuleSoft Platform Architect',
  'mulesoft-integration-architect': 'Salesforce Certified MuleSoft Platform Integration Architect',
  // Accredited Professional
  'advanced-field-service-ap': 'Salesforce Certified Advanced Field Service Accredited Professional',
  'b2b-commerce-admin-ap': 'Salesforce Certified B2B Commerce Admin Accredited Professional',
  'b2b-commerce-developer-ap': 'Salesforce Certified B2B Commerce Developer Accredited Professional',
  'communications-cloud-ap': 'Salesforce Certified Communications Cloud Accredited Professional',
  'consumer-goods-cloud-ap': 'Salesforce Certified Consumer Goods Cloud Accredited Professional',
  'consumer-goods-tpm-ap': 'Salesforce Certified Consumer Goods Cloud Trade Promotion Management Accredited Professional',
  'contact-center-ap': 'Salesforce Certified Contact Center Accredited Professional',
  'cpq-billing-ap': 'Salesforce Certified CPQ and Billing Consultant Accredited Professional',
  'energy-utilities-ap': 'Salesforce Certified Energy and Utilities Cloud Accredited Professional',
  'financial-services-cloud-ap': 'Salesforce Certified Financial Services Cloud Accredited Professional',
  'health-cloud-ap': 'Salesforce Certified Health Cloud Accredited Professional',
  'heroku-developer-ap': 'Salesforce Certified Heroku Developer Accredited Professional',
  'loyalty-management-ap': 'Salesforce Certified Loyalty Management Accredited Professional',
  'manufacturing-cloud-ap': 'Salesforce Certified Manufacturing Cloud Accredited Professional',
  'marketing-cloud-advanced-cross-channel-ap':
    'Salesforce Certified Marketing Cloud Advanced Cross Channel Accredited Professional',
  'marketing-cloud-intelligence-ap': 'Salesforce Certified Marketing Cloud Intelligence Accredited Professional',
  'marketing-cloud-personalization-ap': 'Salesforce Certified Marketing Cloud Personalization Accredited Professional',
  'media-cloud-ap': 'Salesforce Certified Media Cloud Accredited Professional',
  'net-zero-cloud-ap': 'Salesforce Certified Net Zero Cloud Accredited Professional',
  'order-management-admin-ap': 'Salesforce Certified Order Management Administrator Accredited Professional',
  'order-management-developer-ap': 'Salesforce Certified Order Management Developer Accredited Professional',
  'process-automation-ap': 'Salesforce Certified Process Automation Accredited Professional',
  'public-sector-solutions-ap': 'Salesforce Certified Public Sector Solutions Accredited Professional',
  // Sales
  'sales-foundations': 'Salesforce Certified Agentforce Sales Foundations',
  // Designer
  'strategy-designer': 'Salesforce Certified Platform Strategy Designer',
  'ux-designer': 'Salesforce Certified Platform User Experience Designer',
  // Tableau
  'tableau-architect': 'Salesforce Certified Tableau Architect',
  'tableau-consultant': 'Salesforce Certified Tableau Consultant',
  'tableau-data-analyst': 'Salesforce Certified Tableau Data Analyst',
  'tableau-desktop-foundations': 'Salesforce Certified Tableau Desktop Foundations',
  'tableau-server-administrator': 'Salesforce Certified Tableau Server Administrator',
}
