/**
 * Exam prep content per certification: tips, prerequisites, focus areas, study strategy.
 * 
 * CONTENT ORIGINALITY: All exam tips, prerequisites, focus areas, and study strategies are
 * ORIGINAL content written specifically for this site. They are NOT copied from other study
 * guides, websites, or exam prep resources. Each certification has unique, original content
 * to ensure Google can properly index and rank our pages (duplicate content hurts SEO).
 * 
 * Differentiator: actionable, exam-focused content you won't find in one place elsewhere.
 */

export interface ExamPrepContent {
  examTips: string[]
  prerequisites: string[]
  focusAreas: string[]
  studyStrategy: string
  whyItMatters?: string
}

const DEFAULT_PREP: ExamPrepContent = {
  examTips: [
    'Study the highest-weight sections first—they have the most questions.',
    'Use the official Trailhead trailmix; align your study with the exam outline.',
    'Take timed practice exams to build pacing (about 1.5–2 min per question).',
    'Review wrong answers and understand why the correct option is right.',
    'Book the exam when you consistently score 80%+ on practice tests.',
  ],
  prerequisites: ['Hands-on experience in a Salesforce org', 'Familiarity with the exam outline'],
  focusAreas: ['Highest-weighted sections', 'Scenario-based questions', 'Setup and configuration'],
  studyStrategy: 'Start with the sections that have the most weight. Use Trailhead, hands-on practice, and practice questions. Book the exam only after you can explain concepts and pass timed practice tests.',
}

export const EXAM_PREP_CONTENT: Record<string, ExamPrepContent> = {
  administrator: {
    examTips: [
      'Configuration and Setup + Object Manager together are ~40%—master Lightning App Builder and Object Manager first.',
      'Know the difference between Process Builder, Flow, and Workflow (and when to use each).',
      'Security is always tested: roles, profiles, permission sets, sharing rules, OWD.',
      'Practice building reports (summary, matrix, joined) and dashboards from scratch.',
      'Review standard objects: Account, Contact, Lead, Opportunity, Case—and their relationships.',
    ],
    prerequisites: ['6+ months Salesforce Admin experience', 'Platform Fundamentals or equivalent knowledge'],
    focusAreas: ['Configuration and Setup', 'Object Manager and Lightning App Builder', 'Security and Access', 'Automation (Flow vs Workflow)'],
    studyStrategy: 'Spend 40% of study time on Configuration, Object Manager, and Lightning App Builder. Use a Developer Edition org to practice. Take full-length practice exams under time pressure.',
    whyItMatters: 'The Admin cert is the gateway to most Salesforce roles. It is often required for Consultant and Developer paths.',
  },
  'advanced-administrator': {
    ...DEFAULT_PREP,
    examTips: [
      'Security and Organization Setup are heavily weighted—know sharing, roles, and license types.',
      'Understand advanced automation: flows, process builder, approval processes.',
      'Be ready for scenario questions that combine multiple features.',
      'Know limits: roll-up summary fields, workflow rules, validation rules per object.',
    ],
    prerequisites: ['Salesforce Certified Administrator', '12+ months admin experience'],
    focusAreas: ['Security and Access', 'Organization Setup', 'Automation', 'Standard and Custom Objects'],
    studyStrategy: 'Build on your Admin knowledge. Focus on complex sharing scenarios, advanced automation, and cross-object reporting. Practice explaining trade-offs (e.g., when to use Flow vs Process Builder).',
  },
  'app-builder': {
    ...DEFAULT_PREP,
    examTips: [
      'Data Modeling and User Interface are ~42% combined—master relationships, page layouts, record types.',
      'Business Logic and Process Automation is the largest section; know Flow and validation rules well.',
      'Understand when to use Master-Detail vs Lookup and cascade delete behavior.',
      'Practice creating apps with Lightning App Builder and assigning to profiles.',
    ],
    prerequisites: ['Platform experience', 'Administrator cert recommended'],
    focusAreas: ['Data Modeling', 'User Interface (Lightning)', 'Business Logic and Process Automation', 'Reports and Dashboards'],
    studyStrategy: 'Focus on declarative development: no code. Build a small app end-to-end (objects, relationships, automation, reports, dashboard). Align each piece with the exam outline.',
  },
  'sales-cloud': {
    ...DEFAULT_PREP,
    examTips: [
      'Solution Design is 25%—practice translating business requirements into Salesforce features.',
      'Know Lead conversion, assignment rules, and lead lifecycle inside out.',
      'Opportunity management: stages, products, forecasting, territory management.',
      'Be ready for “what would you recommend?” scenario questions.',
    ],
    prerequisites: ['Salesforce Certified Administrator', 'Sales Cloud implementation experience'],
    focusAreas: ['Solution Design', 'Sales Cloud Data Model', 'Lead and Opportunity Management', 'Analytics'],
    studyStrategy: 'Think like a consultant. Given a scenario, recommend the right features and configuration. Study the Sales Cloud Implementation Guide and practice with sample requirements.',
    whyItMatters: 'Sales Cloud Consultant is a top cert for implementation and consulting roles.',
  },
  'service-cloud': {
    ...DEFAULT_PREP,
    examTips: [
      'Solution Design is 25%—focus on case management, entitlements, and knowledge.',
      'Know Omnichannel, queues, case assignment, and escalation.',
      'Understand Knowledge article types, data categories, and deflection.',
      'Practice scenario questions: “Customer wants X; what do you configure?”',
    ],
    prerequisites: ['Salesforce Certified Administrator', 'Service Cloud experience'],
    focusAreas: ['Solution Design', 'Case and Knowledge Management', 'Omnichannel', 'Service Analytics'],
    studyStrategy: 'Map exam sections to real Service Cloud features. Build a small service org: cases, knowledge, queues, and a simple flow. Practice explaining design decisions.',
  },
  'developer-1': {
    ...DEFAULT_PREP,
    examTips: [
      'Logic and User Interface are 50% combined—Apex triggers, LWC, and when to use each.',
      'Know governor limits: SOQL 100, DML 150, etc., and how to avoid hitting them.',
      'Testing: minimum code coverage, positive and negative tests, Test.runAs().',
      'Understand @AuraEnabled, @InvocableMethod, and when to use REST vs SOAP.',
    ],
    prerequisites: ['Programming experience (Java, C#, or similar)', 'Administrator or App Builder recommended'],
    focusAreas: ['Apex and Triggers', 'Lightning Web Components', 'Testing and Deployment', 'Governor Limits'],
    studyStrategy: 'Code daily in a dev org. Build a small LWC + Apex feature and write tests. Memorize key governor limits and practice debugging scenarios.',
    whyItMatters: 'PD1 is the standard developer cert. It is required for many technical and architect paths.',
  },
  'developer-2': {
    ...DEFAULT_PREP,
    examTips: [
      'Architecture and Logic are heavily weighted—design patterns, trigger frameworks, async Apex.',
      'Know when to use Queueable, Batch, Future, and Scheduled Apex.',
      'Understand namespaced packages, unlocked packages, and dependency management.',
      'Be ready for “how would you design?” and “what is the best approach?” questions.',
    ],
    prerequisites: ['Salesforce Certified Platform Developer', '2+ years development experience'],
    focusAreas: ['Architecture and Design Patterns', 'Advanced Apex and LWC', 'Testing and Deployment', 'Integration'],
    studyStrategy: 'Focus on design and best practices, not just syntax. Review trigger frameworks, dependency injection, and package development. Practice explaining trade-offs.',
  },
  'email-specialist': {
    ...DEFAULT_PREP,
    examTips: [
      'Email Content and Send Management are 45%—AMPscript, content blocks, send time optimization.',
      'Know Data Extensions, Sendable Data Extensions, and list vs data extension use cases.',
      'Tracking: opens, clicks, unsubscribes, and how to configure in Email Studio.',
      'Review Journey Builder and Automation Studio for automated sends.',
    ],
    prerequisites: ['Marketing Cloud access', 'Email marketing basics'],
    focusAreas: ['Subscriber and List Management', 'Email Content (AMPscript)', 'Send Management', 'Tracking and Analytics'],
    studyStrategy: 'Use a Marketing Cloud account or sandbox. Build an email with dynamic content, a journey, and a send. Align each activity with the exam outline.',
  },
  'platform-foundations': {
    ...DEFAULT_PREP,
    examTips: [
      'All three sections are roughly equal—cover the whole outline.',
      'Know standard objects and the basic data model (Account, Contact, Lead, Opportunity).',
      'Understand navigation: App Launcher, list views, and basic reports.',
      'No coding; focus on concepts and “what is this used for?”',
    ],
    prerequisites: ['Trailhead or introductory Salesforce experience'],
    focusAreas: ['Customer 360 Platform Basics', 'Navigation and Data Model', 'Reports and Dashboards'],
    studyStrategy: 'Complete the official Trailhead trailmix. Use a Developer Edition org to click through every feature mentioned in the outline. This is an entry-level cert—breadth over depth.',
    whyItMatters: 'The first step on the Salesforce credential path; often required before Administrator.',
  },
  'ai-associate': {
    ...DEFAULT_PREP,
    examTips: [
      'AI Concepts and Einstein Capabilities are 70%—know what each Einstein product does.',
      'Understand Responsible AI: bias, transparency, and ethical use.',
      'Know where Einstein appears in Sales, Service, and Marketing Cloud.',
      'Review Trailhead AI modules and the official exam guide.',
    ],
    prerequisites: ['Platform or CRM basics', 'Interest in AI features'],
    focusAreas: ['AI Concepts and Salesforce AI', 'Einstein Capabilities', 'Responsible AI'],
    studyStrategy: 'Complete the Einstein and Responsible AI Trailhead trails. Focus on product names, use cases, and when to recommend which feature. No coding.',
  },
  'data-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'All four domains are 25%—study the full outline evenly.',
      'Data Modeling: normalization, LDV, big objects, external objects.',
      'Know Identity and Access Management architect concepts (SSO, SAML, OAuth).',
      'Integration and Development Lifecycle: when to use what, and governance.',
    ],
    prerequisites: ['Application Architect', 'System Architect', 'Strong data and integration experience'],
    focusAreas: ['Data Architecture', 'Integration Architecture', 'Identity and Access Management', 'Development Lifecycle'],
    studyStrategy: 'The Data Architect cert covers data modeling, LDV, identity, integration, and development lifecycle. Study each domain separately, then practice cross-domain scenario questions. Review sample scenarios from CTA prep materials.',
  },
  'application-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'Each of the four pillars is 25%—no section can be skipped.',
      'Data Architecture: data model, LDV, integration patterns for data.',
      'Identity and Access: SSO, federation, user lifecycle.',
      'Be ready for “design a solution that meets X and Y requirements.”',
    ],
    prerequisites: ['Multiple architect-level certs', 'Years of implementation experience'],
    focusAreas: ['Data Architecture', 'Integration Architecture', 'Identity and Access Management', 'Development Lifecycle'],
    studyStrategy: 'Treat each pillar as a mini-exam. Use CTA scenario practice to get used to open-ended design questions. Time management is critical.',
  },
  'experience-cloud': {
    ...DEFAULT_PREP,
    examTips: [
      'Solution Design and Site Setup are 50%—know templates, sharing, and audiences.',
      'Understand Sharing Sets, external users, and how to expose records to communities.',
      'Know the difference between Experience Cloud and Sites (Classic).',
      'Practice configuring a sample site: branding, pages, and sharing.',
    ],
    prerequisites: ['Salesforce Certified Administrator', 'Experience Cloud or Community Cloud experience'],
    focusAreas: ['Solution Design and Strategy', 'Site Setup and Configuration', 'Sharing and Security', 'Content and Personalization'],
    studyStrategy: 'Build a small Experience Cloud site from scratch. Configure sharing, audiences, and a few pages. Align each step with the exam outline.',
  },
  'field-service': {
    ...DEFAULT_PREP,
    examTips: [
      'Scheduling and Mobile are 50%—understand dispatch, Gantt, and mobile app configuration.',
      'Know work orders, service appointments, and the field service data model.',
      'Understand optimization (scheduling policies) and manual vs automatic dispatch.',
      'Review assets, product inventory, and parts ordering if applicable.',
    ],
    prerequisites: ['Salesforce Certified Administrator', 'Field Service experience'],
    focusAreas: ['Solution Design', 'Scheduling and Dispatch', 'Mobile and Execution', 'Assets and Inventory'],
    studyStrategy: 'Use a Field Service trial or dev org. Run through scheduling, dispatch, and mobile execution. Focus on “how do you configure X?” scenario questions.',
  },
  'slack-administrator': {
    ...DEFAULT_PREP,
    examTips: [
      'Know Slack Admin settings: org-wide settings, channels, and permissions.',
      'Understand Slack Connect and shared channels with external orgs.',
      'Workflow Builder and integrations (Salesforce, etc.) are commonly tested.',
      'Review security and compliance: DLP, eDiscovery, retention.',
    ],
    prerequisites: ['Slack admin experience', 'Salesforce basics helpful'],
    focusAreas: ['Slack Setup and Configuration', 'Channels and Workspace', 'Policies and Permissions', 'Integrations'],
    studyStrategy: 'Administer a Slack workspace (or use a sandbox). Configure channels, permissions, and at least one integration. Align with the official exam guide.',
  },
  'tableau-desktop-foundations': {
    ...DEFAULT_PREP,
    examTips: [
      'Connecting to Data and Dimensions/Measures are 50%—know data types and the shelf.',
      'Views and Dashboards are 35%—build charts and dashboards from scratch.',
      'Understand filters: context, dimensions, measures, and filter order.',
      'No LOD or advanced calcs; focus on basics.',
    ],
    prerequisites: ['Tableau Desktop access', 'Basic data familiarity'],
    focusAreas: ['Connecting to Data', 'Dimensions and Measures', 'Views and Dashboards', 'Filters and Sorting'],
    studyStrategy: 'Use Tableau Desktop with sample data. Build 5–10 different chart types and at least two dashboards. Complete the official Tableau Desktop fundamentals training.',
  },
  'technical-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'Solution Design is 30%—practice whiteboarding end-to-end solutions.',
      'Know security, integration, and data architecture deeply.',
      'The Review Board is presentation and Q&A—practice explaining and defending designs.',
      'Review past CTA scenario examples and time yourself.',
    ],
    prerequisites: ['Application Architect', 'System Architect', 'Years of complex implementation experience'],
    focusAreas: ['Solution Design', 'Security and Integration', 'Data and Performance', 'Governance and Presentation'],
    studyStrategy: 'The CTA is a two-step process: Evaluation (scenario + MC) and Review Board (present and defend). Practice designing under time pressure and answering “why did you choose X?”',
    whyItMatters: 'The CTA is the highest Salesforce credential and signals expert-level architecture and communication skills.',
  },
  'agentforce-specialist': {
    ...DEFAULT_PREP,
    examTips: [
      'Know Agentforce configuration: agents, prompts, and data access.',
      'Understand how Agentforce fits with platform security and sharing.',
      'Practice optimizing agent responses and handling edge cases.',
      'Review Trailhead Agentforce modules and release notes.',
    ],
    prerequisites: ['Platform Administrator knowledge', 'Hands-on Agentforce experience'],
    focusAreas: ['Agentforce Configuration', 'Platform and Security', 'Agent Capabilities', 'Integration'],
    studyStrategy: 'Use an org with Agentforce enabled. Configure at least one agent and test with real data. Align with the official exam outline.',
  },
  'business-analyst': {
    ...DEFAULT_PREP,
    examTips: [
      'Requirements and Solution Design are 50%—practice discovery and documentation.',
      'Know stakeholder collaboration and how to translate business needs into Salesforce.',
      'Understand success metrics and analytics for solution validation.',
      'Be ready for “how would you gather requirements?” and “what would you recommend?”',
    ],
    prerequisites: ['Business analysis or product experience', 'Salesforce basics'],
    focusAreas: ['Requirements and Discovery', 'Stakeholder Collaboration', 'Solution Design', 'Analytics'],
    studyStrategy: 'Think like a BA: discovery, documentation, and recommendation. Practice writing user stories and mapping them to Salesforce features. Review the exam outline for deliverables.',
  },
  'cpq-administrator': {
    ...DEFAULT_PREP,
    examTips: [
      'Products and Pricing are 55%—product rules, price rules, and configuration.',
      'Know the CPQ data model: Product, Price Book, Quote, Contract.',
      'Understand quote line editor, configuration attributes, and bundles.',
      'Practice “how do you configure X?” for common CPQ scenarios.',
    ],
    prerequisites: ['Salesforce Certified Administrator', 'CPQ or quoting experience'],
    focusAreas: ['CPQ Data Model', 'Products and Pricing', 'Quoting and Configuration', 'Integration'],
    studyStrategy: 'Use a CPQ sandbox. Configure products, price rules, and a full quote flow. Align each feature with the exam outline.',
  },
  'data-360-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'Data Cloud Architecture and Data Model are 50%—know identity resolution and data model.',
      'Understand activation (Marketing, Sales, Service) and segments.',
      'Know governance: data quality, consent, and retention.',
      'Review Data Cloud setup and connector types.',
    ],
    prerequisites: ['Salesforce CRM experience', 'Data or marketing background helpful'],
    focusAreas: ['Data Cloud Architecture', 'Data Model and Identity', 'Activation and Insights', 'Governance'],
    studyStrategy: 'Use a Data Cloud trial or sandbox. Build a data model, identity resolution, and at least one activation. Align with the official exam guide.',
  },
  'javascript-developer-i': {
    ...DEFAULT_PREP,
    examTips: [
      'LWC and Aura are 30%—know component lifecycle, decorators, and events.',
      'JavaScript fundamentals: ES6+, async, DOM, and debugging.',
      'Understand when to use LWC vs Aura and migration considerations.',
      'Testing: Jest for LWC, and debugging in browser and VS Code.',
    ],
    prerequisites: ['JavaScript experience', 'Platform Developer I recommended'],
    focusAreas: ['JavaScript Fundamentals', 'LWC and Aura', 'Debugging and Testing', 'Performance'],
    studyStrategy: 'Build at least two LWCs (one with Apex). Practice debugging and unit testing. Memorize key decorators and lifecycle hooks.',
  },
  'marketing-cloud-engagement-admin': {
    ...DEFAULT_PREP,
    examTips: [
      'All four sections are 25%—cover Setup, Subscriber/Data, Content/Journey, Analytics.',
      'Know subscriber data model, data extensions, and sendable DEs.',
      'Understand Journey Builder, Email Studio, and Automation Studio.',
      'Review Setup: business units, users, and permissions.',
    ],
    prerequisites: ['Marketing Cloud access', 'Email or marketing experience'],
    focusAreas: ['Marketing Cloud Setup', 'Subscriber and Data', 'Content and Journey Builder', 'Analytics'],
    studyStrategy: 'Use a Marketing Cloud account. Configure a journey, an email with dynamic content, and reports. Align with the exam outline.',
  },
  'mulesoft-developer-i': {
    ...DEFAULT_PREP,
    examTips: [
      'Mule Applications and DataWeave are 55%—build flows and transform data.',
      'Know Anypoint Platform: design center, runtime, and deployment.',
      'Understand connectors, error handling, and logging.',
      'Practice building a simple API and a flow that calls an external system.',
    ],
    prerequisites: ['Programming experience', 'Basic integration concepts'],
    focusAreas: ['Anypoint Platform', 'Mule Applications', 'DataWeave and APIs', 'Testing and Deployment'],
    studyStrategy: 'Use Anypoint Platform. Build at least one API and one integration. Practice DataWeave transformations. Align with the official exam guide.',
  },
  'mulesoft-integration-foundations': {
    ...DEFAULT_PREP,
    examTips: [
      'Integration Concepts and Anypoint Platform are 70%—know APIs and design.',
      'Understand REST, API design, and basic security (OAuth).',
      'No heavy coding; focus on concepts and “what is this used for?”',
      'Complete the MuleSoft Integration Fundamentals trail on Trailhead.',
    ],
    prerequisites: ['Basic IT or developer background', 'Interest in integration'],
    focusAreas: ['Integration Concepts', 'Anypoint Platform Basics', 'APIs and Design'],
    studyStrategy: 'Complete the official Trailhead trailmix. Use Anypoint Platform to explore design center and runtime. Breadth over depth for this entry-level cert.',
  },
  'nonprofit-cloud': {
    ...DEFAULT_PREP,
    examTips: [
      'Nonprofit Cloud Data Model and Program/Case are 50%—know NPSP and NPC objects.',
      'Understand donations, households, and program management.',
      'Know reporting: roll-ups, dashboards, and common nonprofit metrics.',
      'Review NPC release notes and implementation guides.',
    ],
    prerequisites: ['Salesforce Administrator', 'Nonprofit or NPSP experience'],
    focusAreas: ['Nonprofit Cloud Data Model', 'Program and Case Management', 'Donations and Engagement', 'Reporting'],
    studyStrategy: 'Use a Nonprofit Cloud or NPSP org. Configure programs, cases, and donations. Align with the exam outline.',
  },
  'pardot-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'Lead Management and Email/Engagement are 50%—know automation and scoring.',
      'Understand Account Engagement (Pardot) setup and Salesforce connector.',
      'Know reporting: engagement metrics, ROI, and attribution.',
      'Be ready for “how would you implement X?” scenario questions.',
    ],
    prerequisites: ['Salesforce Certified Administrator', 'Account Engagement (Pardot) experience'],
    focusAreas: ['Account Engagement Setup', 'Lead Management', 'Email and Engagement', 'Analytics and ROI'],
    studyStrategy: 'Use a Pardot/Account Engagement account. Configure scoring, automation, and at least one campaign. Align with the exam outline.',
  },
  'revenue-cloud-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'CPQ Configuration and Quoting/Contracts are 55%—know product and price rules.',
      'Understand the Revenue Cloud data model and CPQ + Billing integration.',
      'Know contract lifecycle and renewal scenarios.',
      'Practice “how do you configure X?” for CPQ and Billing.',
    ],
    prerequisites: ['Salesforce Certified Administrator', 'CPQ or Billing experience'],
    focusAreas: ['Revenue Cloud Data Model', 'CPQ Configuration', 'Quoting and Contracts', 'Analytics'],
    studyStrategy: 'Use a Revenue Cloud or CPQ sandbox. Configure products, pricing, quotes, and contracts. Align with the exam outline.',
  },
  'tableau-data-analyst': {
    ...DEFAULT_PREP,
    examTips: [
      'Data Connection/Prep and Calculations are 50%—know LOD and table calcs.',
      'Visualization and Dashboards are 35%—build various chart types and dashboards.',
      'Understand dimensions vs measures and the shelf (Rows, Columns, Marks).',
      'Practice building a dashboard with filters and actions.',
    ],
    prerequisites: ['Tableau Desktop experience', 'Data analysis basics'],
    focusAreas: ['Data Connection and Prep', 'Calculations and LOD', 'Visualization and Dashboards', 'Analysis and Insights'],
    studyStrategy: 'Use Tableau Desktop with sample data. Build 5+ chart types, use LOD expressions, and create a dashboard with interactivity. Align with the exam outline.',
  },
  'ux-designer': {
    ...DEFAULT_PREP,
    examTips: [
      'Research and Prototyping + Design and Delivery are 70%—know the design process.',
      'Understand UX research methods and when to use each.',
      'Know accessibility and inclusive design basics.',
      'Be ready for “what would you do next?” and “what method would you use?”',
    ],
    prerequisites: ['UX or design experience', 'Salesforce exposure helpful'],
    focusAreas: ['UX Design Principles', 'Research and Prototyping', 'Design and Delivery'],
    studyStrategy: 'Review the official exam guide and align with UX best practices. Practice explaining your design process and trade-offs. Use Trailhead UX modules.',
  },
  // Architect certifications
  'integration-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'Integration Architecture and Patterns are 55%—know when to use REST, SOAP, and event-driven patterns.',
      'Understand identity and access management for integrations (OAuth, SAML, certificates).',
      'Know integration patterns: point-to-point, hub-and-spoke, publish-subscribe.',
      'Be ready for "how would you integrate X with Y?" scenario questions.',
    ],
    prerequisites: ['Application Architect', 'System Architect', 'Strong integration experience'],
    focusAreas: ['Integration Architecture', 'Integration Patterns', 'Identity and Access', 'Development Lifecycle'],
    studyStrategy: 'Study integration patterns and when to use each. Practice designing end-to-end integration solutions. Review CTA prep materials for complex scenarios.',
  },
  'sharing-visibility-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'Sharing Model and Visibility/Security are 60%—know OWD, sharing rules, and data access patterns.',
      'Understand when to use private, public read-only, public read/write, and controlled by parent.',
      'Know sharing calculation and performance implications of complex sharing models.',
      'Be ready for "how would you design sharing for X requirement?" questions.',
    ],
    prerequisites: ['Application Architect', 'System Architect', 'Deep security and sharing experience'],
    focusAreas: ['Sharing Model', 'Visibility and Security', 'Data Access Patterns', 'Best Practices'],
    studyStrategy: 'Design sharing models for complex scenarios. Understand performance implications and best practices. Practice explaining trade-offs between different sharing approaches.',
  },
  'system-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'All four pillars are 25%—no section can be skipped.',
      'Data Architecture: LDV, data modeling, integration patterns for data.',
      'Integration Architecture: APIs, middleware, event-driven architecture.',
      'Be ready for "design a solution that meets X and Y requirements."',
    ],
    prerequisites: ['Application Architect', 'Years of complex implementation experience'],
    focusAreas: ['Data Architecture', 'Integration Architecture', 'Sharing and Visibility', 'Development Lifecycle'],
    studyStrategy: 'Treat each pillar as a mini-exam. Use CTA scenario practice to get used to open-ended design questions. Time management is critical.',
  },
  'identity-access-management-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'Identity and SSO + Access Management are 60%—know SAML, OAuth, SSO flows, and user provisioning.',
      'Understand federation, delegated authentication, and when to use each.',
      'Know security and compliance: MFA, session management, audit trails.',
      'Be ready for "how would you implement SSO for X scenario?" questions.',
    ],
    prerequisites: ['Application Architect', 'System Architect', 'Identity and security experience'],
    focusAreas: ['Identity and Single Sign-On', 'Access Management', 'Security and Compliance', 'Integration'],
    studyStrategy: 'Design identity solutions for various scenarios. Understand SSO flows, federation, and user lifecycle management. Practice explaining security trade-offs.',
  },
  'dev-lifecycle-deployment-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'CI/CD and Version Control is 30%—know Git workflows, CI/CD pipelines, and deployment strategies.',
      'Understand release management: sandboxes, change sets, unlocked packages, source tracking.',
      'Know environments and metadata: what goes where, and governance.',
      'Be ready for "how would you deploy X?" and "what is the best approach?" questions.',
    ],
    prerequisites: ['Application Architect', 'System Architect', 'DevOps and deployment experience'],
    focusAreas: ['Release Management', 'Environments and Metadata', 'CI/CD and Version Control', 'Governance'],
    studyStrategy: 'Set up a CI/CD pipeline. Practice deploying with different methods. Understand governance and best practices for enterprise deployments.',
  },
  'technical-architect-evaluation': {
    ...DEFAULT_PREP,
    examTips: [
      'Scenario Analysis is 40%—practice reading complex scenarios and identifying requirements.',
      'Solution Design is 35%—know how to design secure, scalable, integrated solutions.',
      'Time management is critical—you have limited time for scenario analysis and design.',
      'Review past CTA evaluation scenarios and practice under time pressure.',
    ],
    prerequisites: ['Application Architect', 'System Architect', 'Years of complex implementation experience'],
    focusAreas: ['Scenario Analysis', 'Solution Design', 'Technical Knowledge'],
    studyStrategy: 'Practice analyzing scenarios quickly. Design solutions under time pressure. Review CTA prep materials and past scenario examples.',
  },
  'technical-architect-review-board': {
    ...DEFAULT_PREP,
    examTips: [
      'Presentation and Design Defense are 70%—practice explaining and defending your designs.',
      'Know your solution inside and out—you will be asked "why did you choose X?"',
      'Practice handling tough questions and alternative approaches.',
      'Time your presentation—you have limited time to present and defend.',
    ],
    prerequisites: ['Passed Technical Architect Evaluation', 'Strong communication skills'],
    focusAreas: ['Presentation', 'Design Defense', 'Board Q&A'],
    studyStrategy: 'Practice presenting your designs to peers. Anticipate questions and prepare answers. Review CTA review board prep materials and practice sessions.',
  },
  'b2b-solution-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'B2B Commerce Architecture is 30%—know catalog, pricing, checkout, and integration patterns.',
      'Understand B2B-specific features: buyer groups, contracts, payment terms.',
      'Know integration patterns: ERP, PIM, payment gateways.',
      'Be ready for "how would you architect X for B2B?" questions.',
    ],
    prerequisites: ['B2B Commerce experience', 'Architect-level knowledge'],
    focusAreas: ['B2B Commerce Architecture', 'Catalog and Pricing', 'Checkout and Integration', 'Best Practices'],
    studyStrategy: 'Design B2B commerce solutions. Understand buyer journeys, catalog management, and integration requirements. Practice explaining architectural decisions.',
  },
  'b2c-commerce-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'B2C Commerce Architecture is 30%—know storefront, experience, and integration patterns.',
      'Understand B2C-specific features: personalization, promotions, cart and checkout.',
      'Know performance and security: caching, CDN, PCI compliance.',
      'Be ready for "how would you architect X for B2C?" questions.',
    ],
    prerequisites: ['B2C Commerce experience', 'Architect-level knowledge'],
    focusAreas: ['B2C Commerce Architecture', 'Storefront and Experience', 'Integration and Data', 'Performance and Security'],
    studyStrategy: 'Design B2C commerce solutions. Understand customer journeys, personalization, and performance optimization. Practice explaining architectural decisions.',
  },
  'b2c-solution-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'B2C Solution Design and Commerce/Experience are 60%—know how to design end-to-end B2C solutions.',
      'Understand integration patterns: CRM, marketing, payment, fulfillment.',
      'Know governance: how to manage multiple sites, brands, and regions.',
      'Be ready for "how would you design X solution?" questions.',
    ],
    prerequisites: ['B2C Commerce Architect', 'Experience Cloud knowledge'],
    focusAreas: ['B2C Solution Design', 'Commerce and Experience', 'Integration', 'Governance'],
    studyStrategy: 'Design end-to-end B2C solutions combining Commerce and Experience Cloud. Understand multi-site governance and integration patterns.',
  },
  'heroku-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'Heroku Architecture is 30%—know dynos, add-ons, buildpacks, and scaling strategies.',
      'Understand scaling and performance: horizontal vs vertical scaling, caching, database optimization.',
      'Know security and data: encryption, compliance, data residency.',
      'Be ready for "how would you architect X on Heroku?" questions.',
    ],
    prerequisites: ['Heroku development experience', 'Architect-level knowledge'],
    focusAreas: ['Heroku Architecture', 'Scaling and Performance', 'Security and Data', 'Integration'],
    studyStrategy: 'Design Heroku-based solutions. Understand dyno types, scaling strategies, and add-ons. Practice explaining architectural decisions for cloud-native apps.',
  },
  'mulesoft-catalyst-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'All four sections are 25%—cover Integration Strategy, Anypoint Platform, API Design, and Best Practices.',
      'Know integration strategy: when to use APIs, ESB, and event-driven patterns.',
      'Understand Anypoint Platform: design center, runtime, and API Manager.',
      'Be ready for "how would you recommend X?" consultant-style questions.',
    ],
    prerequisites: ['MuleSoft experience', 'Integration consulting background'],
    focusAreas: ['Integration Strategy', 'Anypoint Platform', 'API Design', 'Best Practices'],
    studyStrategy: 'Think like a consultant. Practice recommending integration approaches and explaining trade-offs. Use Anypoint Platform to design and deploy APIs.',
  },
  'mulesoft-platform-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'Integration Architecture is 30%—know API-led connectivity and integration patterns.',
      'Understand Anypoint Platform: design center, runtime, API Manager, and governance.',
      'Know API and Security: OAuth, policies, rate limiting, and security best practices.',
      'Be ready for "how would you architect X?" questions.',
    ],
    prerequisites: ['MuleSoft Developer II', 'Architect-level integration experience'],
    focusAreas: ['Integration Architecture', 'Anypoint Platform', 'API and Security', 'Governance'],
    studyStrategy: 'Design integration architectures using API-led connectivity. Understand platform governance and security. Practice explaining architectural decisions.',
  },
  'mulesoft-integration-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'Integration Architecture is 30%—know integration patterns and when to use each.',
      'Understand API Design: REST, SOAP, event-driven, and API versioning.',
      'Know Security and Patterns: authentication, authorization, and common integration patterns.',
      'Be ready for "how would you design X integration?" questions.',
    ],
    prerequisites: ['MuleSoft Platform Architect', 'Deep integration architecture experience'],
    focusAreas: ['Integration Architecture', 'API Design', 'Security and Patterns', 'Lifecycle'],
    studyStrategy: 'Design complex integration architectures. Understand patterns, security, and lifecycle management. Practice explaining trade-offs and architectural decisions.',
  },
  // Accredited Professional certifications
  'advanced-field-service-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'All four sections are 25%—cover Field Service Configuration, Scheduling, Mobile, and Assets.',
      'Know scheduling and dispatch: optimization, Gantt, and manual vs automatic dispatch.',
      'Understand mobile execution: Field Service Mobile app, offline capabilities, and data sync.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Field Service experience', 'Salesforce Administrator'],
    focusAreas: ['Field Service Configuration', 'Scheduling and Dispatch', 'Mobile and Execution', 'Assets and Best Practices'],
    studyStrategy: 'Use a Field Service org. Configure scheduling, dispatch, mobile, and assets. Align each feature with the exam outline.',
  },
  'b2b-commerce-admin-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'B2B Commerce Setup is 30%—know catalog, pricing, buyer groups, and contracts.',
      'Understand catalog and pricing: product catalogs, price lists, and pricing rules.',
      'Know orders and integration: order management, payment, and ERP integration.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['B2B Commerce experience', 'Salesforce Administrator'],
    focusAreas: ['B2B Commerce Setup', 'Catalog and Pricing', 'Orders and Integration', 'Administration'],
    studyStrategy: 'Use a B2B Commerce org. Configure catalog, pricing, buyer groups, and orders. Align with the exam outline.',
  },
  'b2b-commerce-developer-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'B2B Development is 30%—know Cart and Checkout customization, APIs, and integration.',
      'Understand cart and checkout: cart calculation, checkout flows, and payment integration.',
      'Know integration: REST APIs, webhooks, and external system integration.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['B2B Commerce development experience', 'Platform Developer I'],
    focusAreas: ['B2B Development', 'Cart and Checkout', 'Integration', 'Testing'],
    studyStrategy: 'Develop B2B Commerce features. Customize cart and checkout, integrate with external systems. Align with the exam outline.',
  },
  'communications-cloud-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Channels and Flows are 35%—know SMS, voice, email, and messaging channels.',
      'Understand Communications Cloud setup: org configuration, channels, and flows.',
      'Know analytics and best practices: reporting, monitoring, and optimization.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Communications Cloud experience', 'Salesforce Administrator'],
    focusAreas: ['Communications Cloud Setup', 'Channels and Flows', 'Analytics and Best Practices'],
    studyStrategy: 'Use a Communications Cloud org. Configure channels, flows, and analytics. Align with the exam outline.',
  },
  'consumer-goods-cloud-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Consumer Goods Cloud and Retail Execution are 70%—know the CGC data model and retail execution features.',
      'Understand retail execution: visits, surveys, orders, and inventory.',
      'Know integration and analytics: ERP integration, reporting, and dashboards.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Consumer Goods Cloud experience', 'Salesforce Administrator'],
    focusAreas: ['Consumer Goods Cloud', 'Retail Execution', 'Integration and Analytics'],
    studyStrategy: 'Use a Consumer Goods Cloud org. Configure retail execution, visits, and orders. Align with the exam outline.',
  },
  'consumer-goods-tpm-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Trade Promotion Management is 40%—know TPM data model, planning, and execution.',
      'Understand planning and execution: promotion planning, budgets, and execution tracking.',
      'Know analytics: ROI, performance, and reporting.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['TPM experience', 'Consumer Goods Cloud knowledge'],
    focusAreas: ['Trade Promotion Management', 'Planning and Execution', 'Analytics'],
    studyStrategy: 'Use a TPM org. Configure promotions, planning, and execution. Align with the exam outline.',
  },
  'contact-center-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Omnichannel and Flows are 35%—know Contact Center setup, channels, and flows.',
      'Understand Contact Center setup: org configuration, channels, and routing.',
      'Know analytics and best practices: reporting, monitoring, and optimization.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Contact Center experience', 'Salesforce Administrator'],
    focusAreas: ['Contact Center Setup', 'Omnichannel and Flows', 'Analytics and Best Practices'],
    studyStrategy: 'Use a Contact Center org. Configure channels, flows, and analytics. Align with the exam outline.',
  },
  'cpq-billing-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'CPQ and Billing + Quoting and Contracts are 70%—know CPQ configuration, quoting, and billing.',
      'Understand CPQ and Billing: product rules, price rules, quotes, and contracts.',
      'Know billing and revenue: billing processes, revenue recognition, and invoicing.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['CPQ and Billing experience', 'Salesforce Administrator'],
    focusAreas: ['CPQ and Billing', 'Quoting and Contracts', 'Billing and Revenue'],
    studyStrategy: 'Use a CPQ and Billing org. Configure products, pricing, quotes, and billing. Align with the exam outline.',
  },
  'energy-utilities-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Energy and Utilities Cloud is 40%—know the E&U data model, service territories, and work orders.',
      'Understand configuration: service territories, work orders, and asset management.',
      'Know best practices: implementation patterns, reporting, and optimization.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Energy and Utilities Cloud experience', 'Salesforce Administrator'],
    focusAreas: ['Energy and Utilities Cloud', 'Configuration', 'Best Practices'],
    studyStrategy: 'Use an Energy and Utilities Cloud org. Configure service territories, work orders, and assets. Align with the exam outline.',
  },
  'financial-services-cloud-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Financial Services Cloud is 40%—know the FSC data model, households, and financial accounts.',
      'Understand configuration and data: households, accounts, goals, and financial accounts.',
      'Know best practices: implementation patterns, reporting, and compliance.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Financial Services Cloud experience', 'Salesforce Administrator'],
    focusAreas: ['Financial Services Cloud', 'Configuration and Data', 'Best Practices'],
    studyStrategy: 'Use a Financial Services Cloud org. Configure households, accounts, and financial accounts. Align with the exam outline.',
  },
  'health-cloud-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Health Cloud is 40%—know the Health Cloud data model, care plans, and patient management.',
      'Understand care plans and configuration: care plans, care teams, and patient management.',
      'Know best practices: implementation patterns, reporting, and compliance.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Health Cloud experience', 'Salesforce Administrator'],
    focusAreas: ['Health Cloud', 'Care Plans and Configuration', 'Best Practices'],
    studyStrategy: 'Use a Health Cloud org. Configure care plans, care teams, and patient management. Align with the exam outline.',
  },
  'heroku-developer-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Heroku Development and Apps/Add-ons are 70%—know dynos, buildpacks, add-ons, and deployment.',
      'Understand Heroku development: dynos, buildpacks, config vars, and deployment.',
      'Know deployment and best practices: Git deployment, CI/CD, and monitoring.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['Heroku development experience', 'Programming knowledge'],
    focusAreas: ['Heroku Development', 'Apps and Add-ons', 'Deployment and Best Practices'],
    studyStrategy: 'Develop and deploy apps on Heroku. Use add-ons, configure dynos, and set up CI/CD. Align with the exam outline.',
  },
  'loyalty-management-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Loyalty Management is 40%—know loyalty programs, points, rewards, and member management.',
      'Understand program configuration: programs, rules, points, and rewards.',
      'Know integration: API integration, external systems, and data sync.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Loyalty Management experience', 'Salesforce Administrator'],
    focusAreas: ['Loyalty Management', 'Program Configuration', 'Integration'],
    studyStrategy: 'Use a Loyalty Management org. Configure programs, points, and rewards. Align with the exam outline.',
  },
  'manufacturing-cloud-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Manufacturing Cloud is 40%—know the Manufacturing Cloud data model, work orders, and production.',
      'Understand configuration: work orders, production, and inventory.',
      'Know best practices: implementation patterns, reporting, and optimization.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Manufacturing Cloud experience', 'Salesforce Administrator'],
    focusAreas: ['Manufacturing Cloud', 'Configuration', 'Best Practices'],
    studyStrategy: 'Use a Manufacturing Cloud org. Configure work orders, production, and inventory. Align with the exam outline.',
  },
  'marketing-cloud-advanced-cross-channel-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Cross-Channel Strategy and Journey Builder/Email are 70%—know cross-channel marketing and journey design.',
      'Understand cross-channel strategy: email, SMS, push, and social channels.',
      'Know analytics and best practices: reporting, optimization, and compliance.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Marketing Cloud experience', 'Cross-channel marketing knowledge'],
    focusAreas: ['Cross-Channel Strategy', 'Journey Builder and Email', 'Analytics and Best Practices'],
    studyStrategy: 'Use Marketing Cloud. Configure cross-channel journeys, email, and analytics. Align with the exam outline.',
  },
  'marketing-cloud-intelligence-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Marketing Cloud Intelligence is 40%—know Intelligence, Ad Studio, and analytics.',
      'Understand Intelligence: data models, insights, and reporting.',
      'Know Ad Studio and analytics: ad creation, targeting, and performance.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Marketing Cloud Intelligence experience', 'Marketing Cloud knowledge'],
    focusAreas: ['Marketing Cloud Intelligence', 'Ad Studio and Analytics', 'Best Practices'],
    studyStrategy: 'Use Marketing Cloud Intelligence. Configure insights, Ad Studio, and analytics. Align with the exam outline.',
  },
  'marketing-cloud-personalization-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Personalization Strategy and Web/Mobile Personalization are 70%—know personalization strategy and implementation.',
      'Understand personalization strategy: audience segmentation, content, and optimization.',
      'Know web and mobile personalization: implementation, testing, and optimization.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Marketing Cloud Personalization experience', 'Marketing Cloud knowledge'],
    focusAreas: ['Personalization Strategy', 'Web and Mobile Personalization', 'Analytics and Best Practices'],
    studyStrategy: 'Use Marketing Cloud Personalization. Configure personalization strategies, web and mobile. Align with the exam outline.',
  },
  'media-cloud-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Media Cloud is 45%—know Media Cloud setup, configuration, and best practices.',
      'Understand Media Cloud: setup, configuration, and media management.',
      'Know best practices: implementation patterns, reporting, and optimization.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Media Cloud experience', 'Salesforce Administrator'],
    focusAreas: ['Media Cloud', 'Configuration and Best Practices'],
    studyStrategy: 'Use Media Cloud. Configure setup, media management, and reporting. Align with the exam outline.',
  },
  'net-zero-cloud-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Net Zero Cloud is 45%—know Net Zero Cloud setup, sustainability, and reporting.',
      'Understand Net Zero Cloud: setup, sustainability tracking, and reporting.',
      'Know sustainability and reporting: carbon tracking, goals, and compliance.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Net Zero Cloud experience', 'Salesforce Administrator'],
    focusAreas: ['Net Zero Cloud', 'Sustainability and Reporting'],
    studyStrategy: 'Use Net Zero Cloud. Configure sustainability tracking, goals, and reporting. Align with the exam outline.',
  },
  'order-management-admin-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Order Management is 40%—know Order Management setup, configuration, and best practices.',
      'Understand Order Management: setup, orchestration, and fulfillment.',
      'Know best practices: implementation patterns, reporting, and optimization.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Order Management experience', 'Salesforce Administrator'],
    focusAreas: ['Order Management', 'Configuration', 'Best Practices'],
    studyStrategy: 'Use Order Management. Configure orchestration, fulfillment, and reporting. Align with the exam outline.',
  },
  'order-management-developer-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Order Management Development is 40%—know Order Management development, integration, and APIs.',
      'Understand Order Management development: customization, integration, and APIs.',
      'Know integration and APIs: REST APIs, webhooks, and external system integration.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['Order Management development experience', 'Platform Developer I'],
    focusAreas: ['Order Management Development', 'Integration and APIs', 'Best Practices'],
    studyStrategy: 'Develop Order Management features. Customize orchestration, integrate with external systems. Align with the exam outline.',
  },
  'process-automation-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Process Automation is 40%—know Flow, Process Builder, and automation best practices.',
      'Understand Flow and automation: Flow types, Process Builder, and approval processes.',
      'Know best practices: automation patterns, performance, and governance.',
      'Be ready for "how do you automate X?" questions.',
    ],
    prerequisites: ['Process automation experience', 'Salesforce Administrator'],
    focusAreas: ['Process Automation', 'Flow and Automation', 'Best Practices'],
    studyStrategy: 'Use Flow and Process Builder. Build automation for various scenarios. Align with the exam outline.',
  },
  'public-sector-solutions-ap': {
    ...DEFAULT_PREP,
    examTips: [
      'Public Sector Solutions is 45%—know Public Sector setup, configuration, and best practices.',
      'Understand Public Sector Solutions: setup, configuration, and government-specific features.',
      'Know configuration and best practices: implementation patterns, reporting, and compliance.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Public Sector Solutions experience', 'Salesforce Administrator'],
    focusAreas: ['Public Sector Solutions', 'Configuration and Best Practices'],
    studyStrategy: 'Use Public Sector Solutions. Configure government-specific features and reporting. Align with the exam outline.',
  },
  // Additional certifications
  'email-specialist-practice-test': {
    ...DEFAULT_PREP,
    examTips: [
      'Content and Sends are 35%—know email creation, AMPscript, and send management.',
      'Understand subscriber management: lists, data extensions, and segmentation.',
      'Know tracking and data: opens, clicks, unsubscribes, and reporting.',
      'Practice with Marketing Cloud Email Studio.',
    ],
    prerequisites: ['Marketing Cloud Email Specialist knowledge', 'Email marketing basics'],
    focusAreas: ['Subscriber Management', 'Content and Sends', 'Tracking and Data', 'Best Practices'],
    studyStrategy: 'Use Marketing Cloud Email Studio. Create emails, manage subscribers, and review tracking. Align with the exam outline.',
  },
  'administrator-practice-test': {
    ...DEFAULT_PREP,
    examTips: [
      'All sections are roughly equal—cover Configuration, Security, Automation, Data, and Sales/Service.',
      'Know configuration and setup: Lightning App Builder, Object Manager, and security.',
      'Understand automation: Flow, Process Builder, and Workflow Rules.',
      'Practice with timed practice tests to build pacing.',
    ],
    prerequisites: ['Salesforce Administrator knowledge', 'Platform experience'],
    focusAreas: ['Configuration and Setup', 'Security and Objects', 'Automation', 'Data and Reports', 'Sales and Service'],
    studyStrategy: 'Take timed practice tests. Review wrong answers. Focus on areas where you score below 80%.',
  },
  'pardot-specialist': {
    ...DEFAULT_PREP,
    examTips: [
      'Account Engagement Basics and Lead/List Management are 55%—know Pardot setup and lead management.',
      'Understand Account Engagement basics: setup, connector, and user management.',
      'Know lead and list management: lists, segmentation, and lead assignment.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Account Engagement (Pardot) experience', 'Salesforce Administrator'],
    focusAreas: ['Account Engagement Basics', 'Lead and List Management', 'Email and Automation', 'Reporting'],
    studyStrategy: 'Use Account Engagement (Pardot). Configure setup, lead management, and automation. Align with the exam outline.',
  },
  'marketing-cloud-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'All four sections are 25%—cover Strategy, Subscriber/Data, Email/Journey, and Analytics.',
      'Know Marketing Cloud strategy: multi-channel marketing and campaign design.',
      'Understand subscriber and data management: data extensions, lists, and segmentation.',
      'Be ready for "how would you implement X?" consultant-style questions.',
    ],
    prerequisites: ['Marketing Cloud experience', 'Salesforce Certified Administrator'],
    focusAreas: ['Marketing Cloud Strategy', 'Subscriber and Data Management', 'Email and Journey Builder', 'Analytics and Integration'],
    studyStrategy: 'Think like a consultant. Design Marketing Cloud solutions for various scenarios. Practice explaining recommendations and trade-offs.',
  },
  'nonprofit-success-pack-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'All four sections are 25%—cover NPSP Data Model, Donations, Configuration, and Reporting.',
      'Know NPSP data model: accounts, contacts, households, and donations.',
      'Understand donations and households: gift entry, payment processing, and household management.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['NPSP experience', 'Salesforce Administrator'],
    focusAreas: ['NPSP Data Model', 'Donations and Households', 'Configuration and Automation', 'Reporting and Integration'],
    studyStrategy: 'Use an NPSP org. Configure donations, households, and reporting. Align with the exam outline.',
  },
  'education-cloud-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'All four sections are 25%—cover Education Cloud Data Model, Admissions, Configuration, and Reporting.',
      'Know Education Cloud data model: students, programs, courses, and admissions.',
      'Understand admissions and student lifecycle: application process, enrollment, and student management.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Education Cloud experience', 'Salesforce Administrator'],
    focusAreas: ['Education Cloud Data Model', 'Admissions and Student Lifecycle', 'Configuration and Automation', 'Reporting and Integration'],
    studyStrategy: 'Use an Education Cloud org. Configure admissions, student lifecycle, and reporting. Align with the exam outline.',
  },
  'crm-analytics-einstein-discovery-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'All four sections are 25%—cover CRM Analytics Setup, Data Prep, Lens/Dashboards, and Einstein Discovery.',
      'Know CRM Analytics setup: org setup, data sources, and connections.',
      'Understand data preparation and datasets: data transformation, recipes, and datasets.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['CRM Analytics experience', 'Salesforce Administrator'],
    focusAreas: ['CRM Analytics Setup', 'Data Preparation and Datasets', 'Lens, Dashboards, and Stories', 'Einstein Discovery'],
    studyStrategy: 'Use CRM Analytics. Configure data sources, create datasets, build dashboards, and use Einstein Discovery. Align with the exam outline.',
  },
  'b2c-commerce-developer': {
    ...DEFAULT_PREP,
    examTips: [
      'B2C Commerce Architecture and Storefront/Scripts are 55%—know B2C development and customization.',
      'Understand B2C Commerce architecture: storefront, scripts, and APIs.',
      'Know storefront and scripts: ISML, controllers, and script development.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['B2C Commerce development experience', 'JavaScript knowledge'],
    focusAreas: ['B2C Commerce Architecture', 'Storefront and Scripts', 'Data and APIs', 'Testing and Deployment'],
    studyStrategy: 'Develop B2C Commerce features. Customize storefront, write scripts, and integrate with APIs. Align with the exam outline.',
  },
  'industries-cpq-developer': {
    ...DEFAULT_PREP,
    examTips: [
      'CPQ Data Model and Product/Pricing + Configuration/Scripting are 80%—know CPQ development deeply.',
      'Understand CPQ data model: products, price books, quotes, and configuration.',
      'Know configuration and scripting: product rules, price rules, and CPQ APIs.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['CPQ development experience', 'Platform Developer I'],
    focusAreas: ['CPQ Data Model', 'Product and Pricing', 'Configuration and Scripting', 'Integration'],
    studyStrategy: 'Develop CPQ features. Customize product rules, price rules, and configuration. Align with the exam outline.',
  },
  'marketing-cloud-engagement-developer': {
    ...DEFAULT_PREP,
    examTips: [
      'Marketing Cloud Development and AMPscript/SSJS are 55%—know Marketing Cloud development.',
      'Understand Marketing Cloud development: AMPscript, SSJS, and APIs.',
      'Know API and integration: REST APIs, SOAP APIs, and external system integration.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['Marketing Cloud development experience', 'JavaScript knowledge'],
    focusAreas: ['Marketing Cloud Development', 'AMPscript and SSJS', 'API and Integration', 'Testing and Deployment'],
    studyStrategy: 'Develop Marketing Cloud features. Write AMPscript and SSJS, integrate with APIs. Align with the exam outline.',
  },
  'mulesoft-developer-ii': {
    ...DEFAULT_PREP,
    examTips: [
      'Advanced Mule Development is 30%—know advanced Mule concepts, patterns, and best practices.',
      'Understand API Design and Security: RESTful APIs, OAuth, and API security.',
      'Know error handling and performance: error handling strategies and performance optimization.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['MuleSoft Developer I', 'Advanced Mule development experience'],
    focusAreas: ['Advanced Mule Development', 'API Design and Security', 'Error Handling and Performance', 'Deployment and Operations'],
    studyStrategy: 'Develop advanced Mule applications. Design APIs, handle errors, optimize performance. Align with the exam outline.',
  },
  'mulesoft-hyperautomation-developer': {
    ...DEFAULT_PREP,
    examTips: [
      'Hyperautomation Concepts and RPA/Integration are 55%—know hyperautomation and RPA.',
      'Understand hyperautomation concepts: automation, RPA, and integration patterns.',
      'Know RPA and integration: RPA tools, integration, and automation design.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['MuleSoft development experience', 'RPA knowledge'],
    focusAreas: ['Hyperautomation Concepts', 'RPA and Integration', 'Automation Design', 'Best Practices'],
    studyStrategy: 'Develop hyperautomation solutions. Use RPA tools, design automation, and integrate systems. Align with the exam outline.',
  },
  'slack-developer': {
    ...DEFAULT_PREP,
    examTips: [
      'Slack API/Events and Apps/Workflows are 60%—know Slack development and app creation.',
      'Understand Slack API and Events: Events API, Web API, and event handling.',
      'Know apps and workflows: Slack apps, Workflow Builder, and automation.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['Slack development experience', 'API knowledge'],
    focusAreas: ['Slack API and Events', 'Apps and Workflows', 'Integration with Salesforce', 'Security and Deployment'],
    studyStrategy: 'Develop Slack apps. Use Slack APIs, create workflows, and integrate with Salesforce. Align with the exam outline.',
  },
  'slack-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'All four sections are 25%—cover Slack Strategy, Channels/Workflows, Salesforce Integration, and Governance.',
      'Know Slack strategy and design: workspace design, channel strategy, and adoption.',
      'Understand channels and workflows: channel management, Workflow Builder, and automation.',
      'Be ready for "how would you implement X?" consultant-style questions.',
    ],
    prerequisites: ['Slack experience', 'Salesforce knowledge'],
    focusAreas: ['Slack Strategy and Design', 'Channels and Workflows', 'Salesforce Integration', 'Governance and Best Practices'],
    studyStrategy: 'Think like a consultant. Design Slack solutions, integrate with Salesforce, and plan governance. Align with the exam outline.',
  },
  'omnistudio-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'OmniStudio Overview and Digital Flows/FlexCards are 55%—know OmniStudio configuration and design.',
      'Understand OmniStudio overview: OmniScript, FlexCards, and DataRaptors.',
      'Know digital flows and FlexCards: flow design, card configuration, and data transformation.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['OmniStudio experience', 'Salesforce Administrator'],
    focusAreas: ['OmniStudio Overview', 'Digital Flows and FlexCards', 'Integration and DataRaptors', 'Best Practices'],
    studyStrategy: 'Use OmniStudio. Configure OmniScripts, FlexCards, and DataRaptors. Align with the exam outline.',
  },
  'omnistudio-developer': {
    ...DEFAULT_PREP,
    examTips: [
      'OmniStudio Development and FlexCards/Digital Flows are 60%—know OmniStudio development.',
      'Understand OmniStudio development: OmniScript customization, FlexCard development, and scripting.',
      'Know integration and scripting: DataRaptors, integration procedures, and JavaScript.',
      'Be ready for "how do you develop X?" questions.',
    ],
    prerequisites: ['OmniStudio development experience', 'JavaScript knowledge'],
    focusAreas: ['OmniStudio Development', 'FlexCards and Digital Flows', 'Integration and Scripting', 'Testing and Deployment'],
    studyStrategy: 'Develop OmniStudio features. Customize OmniScripts, develop FlexCards, and write scripts. Align with the exam outline.',
  },
  'sales-foundations': {
    ...DEFAULT_PREP,
    examTips: [
      'Sales Fundamentals and Salesforce CRM Basics are 75%—know sales fundamentals and CRM basics.',
      'Understand sales fundamentals: sales process, customer-centric methodology, and best practices.',
      'Know Salesforce CRM basics: leads, opportunities, accounts, and contacts.',
      'Be ready for "what is X used for?" questions.',
    ],
    prerequisites: ['Sales experience', 'Salesforce basics'],
    focusAreas: ['Sales Fundamentals', 'Salesforce CRM Basics', 'Best Practices'],
    studyStrategy: 'Complete Trailhead Sales Cloud basics. Understand the sales process and CRM fundamentals. Align with the exam outline.',
  },
  'strategy-designer': {
    ...DEFAULT_PREP,
    examTips: [
      'Strategy and Discovery + Solution Design are 65%—know strategy design and discovery methods.',
      'Understand strategy and discovery: discovery methods, stakeholder engagement, and requirements gathering.',
      'Know solution design: experience strategy, solution design, and delivery.',
      'Be ready for "how would you design X?" questions.',
    ],
    prerequisites: ['Strategy and design experience', 'Salesforce knowledge'],
    focusAreas: ['Strategy and Discovery', 'Solution Design', 'Stakeholder and Delivery'],
    studyStrategy: 'Practice strategy design. Use discovery methods, design solutions, and engage stakeholders. Align with the exam outline.',
  },
  'tableau-architect': {
    ...DEFAULT_PREP,
    examTips: [
      'Tableau Architecture is 30%—know Tableau Server architecture, governance, and scalability.',
      'Understand governance and security: user management, permissions, and security models.',
      'Know scalability and performance: server architecture, performance tuning, and optimization.',
      'Be ready for "how would you architect X?" questions.',
    ],
    prerequisites: ['Tableau Server experience', 'Architect-level knowledge'],
    focusAreas: ['Tableau Architecture', 'Governance and Security', 'Scalability and Performance', 'Best Practices'],
    studyStrategy: 'Design Tableau Server architectures. Plan governance, security, and scalability. Align with the exam outline.',
  },
  'tableau-consultant': {
    ...DEFAULT_PREP,
    examTips: [
      'Requirements and Design + Data/Visualization are 65%—know Tableau consulting and solution design.',
      'Understand requirements and design: discovery, requirements gathering, and solution design.',
      'Know data and visualization: data preparation, visualization design, and dashboard creation.',
      'Be ready for "how would you implement X?" consultant-style questions.',
    ],
    prerequisites: ['Tableau experience', 'Consulting background'],
    focusAreas: ['Requirements and Design', 'Data and Visualization', 'Stakeholder and Best Practices'],
    studyStrategy: 'Think like a consultant. Design Tableau solutions, create visualizations, and engage stakeholders. Align with the exam outline.',
  },
  'tableau-server-administrator': {
    ...DEFAULT_PREP,
    examTips: [
      'All four sections are 25%—cover Installation, Security, User/Content Management, and Performance.',
      'Know installation and deployment: Tableau Server installation, configuration, and deployment.',
      'Understand security and authentication: authentication methods, SSL, and security best practices.',
      'Be ready for "how do you configure X?" questions.',
    ],
    prerequisites: ['Tableau Server experience', 'System administration knowledge'],
    focusAreas: ['Installation and Deployment', 'Security and Authentication', 'User and Content Management', 'Performance and Monitoring'],
    studyStrategy: 'Administer Tableau Server. Install, configure security, manage users, and monitor performance. Align with the exam outline.',
  },
}


// Fill in defaults for any cert not in the map above
export function getExamPrepContent(slug: string): ExamPrepContent {
  const custom = EXAM_PREP_CONTENT[slug]
  if (custom) return custom
  return {
    ...DEFAULT_PREP,
    studyStrategy: `Prioritize the highest-weighted sections on the exam (see the weightage above). Use Trailhead, hands-on practice, and full-length practice tests. Schedule the exam when you consistently score 80%+ and can explain concepts clearly.`,
  }
}
