/**
 * Auto-generated by scripts/promote-all-certs-to-associate.mjs
 *
 * EMERGENCY ESCAPE HATCH (currently disabled):
 * If a certification page migration fails catastrophically (type safety issues, content loss, etc.),
 * you can temporarily restore from legacy TSX to unblock traffic:
 *
 * 1. Place the legacy TSX file in src/components/certifications/cert-bodies/{slug}.tsx
 * 2. Re-add the slug to LEGACY_CERT_SLUGS in legacy-cert-slugs.generated.ts (by running cert:promote-associate)
 * 3. Uncomment the dynamic import logic below
 * 4. Verify the legacy component renders correctly
 * 5. FILE A TICKET to complete the migration properly
 *
 * DO NOT leave certs in legacy mode long-term; it bypasses the spike architecture.
 */
import type { ComponentType } from 'react'

export type LegacyCertPageBody = ComponentType

export async function loadLegacyCertBody(_slug: string): Promise<LegacyCertPageBody | null> {
  // Legacy loader is intentionally disabled. Uncomment below only for emergency restoration.
  // const mod = await import(`@/components/certifications/cert-bodies/${_slug}.tsx`)
  //   .catch(() => null)
  // return mod?.default ?? null
  return null
}
