/**
 * Auto-generated by scripts/promote-all-certs-to-associate.mjs
 *
 * EMERGENCY ESCAPE HATCH (currently disabled):
 * If a certification page migration fails catastrophically (type safety issues, content loss, etc.),
 * you can temporarily restore from legacy TSX to unblock traffic:
 *
 * 1. Place the legacy TSX file in src/components/certifications/cert-bodies/{slug}.tsx
 * 2. Re-add the slug to LEGACY_CERT_SLUGS in legacy-cert-slugs.generated.ts (by running cert:promote-associate)
 * 3. Uncomment the dynamic import logic below
 * 4. Verify the legacy component renders correctly
 * 5. FILE A TICKET to complete the migration properly
 *
 * DO NOT leave certs in legacy mode long-term; it bypasses the spike architecture.
 *
 * CLEANUP CRITERIA (when to delete the escape hatch):
 * - LEGACY_CERT_SLUGS remains empty for 2+ releases
 * - cert-migration-status.mjs reports "0 legacy TSX"
 * - No open tickets for legacy fallback restorations
 * - The migration pattern is stable and proven (12+ weeks in production)
 *
 * At that point, remove:
 * - src/lib/cert-page-spike/load-legacy-cert-body.ts
 * - src/lib/cert-page-spike/legacy-cert-slugs.generated.ts
 * - The legacy branch from src/app/certifications/[slug]/page.tsx
 * - LegacySpikeBody type from src/lib/cert-page-spike/types.ts
 */
import type { ComponentType } from 'react'

export type LegacyCertPageBody = ComponentType

export async function loadLegacyCertBody(_slug: string): Promise<LegacyCertPageBody | null> {
  // Legacy loader is intentionally disabled. Uncomment below only for emergency restoration.
  // const mod = await import(`@/components/certifications/cert-bodies/${_slug}.tsx`)
  //   .catch(() => null)
  // return mod?.default ?? null
  return null
}
