#!/usr/bin/env python3
"""Add Key Concepts sections to missing cert pages — batch 3 (net-zero through technical-architect-review-board)."""
import os, re

BASE = '/Users/brahmajikatragadda/Downloads/salesforce-certifications/src/app/certifications'

def kc_block(title, concepts):
    items = ''
    for h, b in concepts:
        items += f'''              <div>
                <p className="font-semibold text-gray-900 mb-1">{h}</p>
                <p>{b}</p>
              </div>\n'''
    return f'''
          {{/* Key Concepts */}}
          <div id="key-concepts" className="mt-12 rounded-xl border border-gray-100 bg-white p-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">{title}</h2>
            <div className="space-y-4 text-sm text-gray-700">
{items}            </div>
          </div>
'''

PAGES = {
  'net-zero-cloud-ap': kc_block('Net Zero Cloud AP: Key Concepts for the Exam', [
    ('Carbon Footprint Data Model',
     'Net Zero Cloud (NZC) stores sustainability data in a specialized data model. Footprint records track greenhouse gas (GHG) emissions, energy consumption, water usage, and waste data. Energy Use records capture electricity, natural gas, and fuel consumption by facility and period. Stationary Combustion, Mobile Combustion, Fugitive Emissions, and Purchased Electricity represent Scope 1 and 2 emission sources. Scope 3 categories (business travel, employee commuting, supply chain) require integration with travel management systems and supplier data. The AP exam tests how NZC objects relate to each other, how to input energy data, and how scope classifications are assigned to emission sources.'),
    ('Emissions Calculations & Emission Factors',
     'Net Zero Cloud calculates GHG emissions by multiplying activity data by an Emission Factor — a coefficient that converts a unit of activity (kWh, liters, miles) into kg CO2e. Emission Factor Libraries contain region-specific and source-specific factors from EPA, IEA, DEFRA, and other bodies. Custom Emission Factors allow organizations to use supplier-specific or measured factors. Scope 2 emissions support both Location-Based (grid average factor) and Market-Based (contractual instruments — RECs, PPAs) calculation methods. The exam tests how to assign emission factors to energy records, the difference between location-based and market-based Scope 2, and how formula-based calculation rules work in NZC.'),
    ('Sustainability Reporting & Disclosures',
     'Net Zero Cloud generates reports aligned with major sustainability frameworks: GRI (Global Reporting Initiative), TCFD (Task Force on Climate-related Financial Disclosures), CDP, and emerging SEC climate disclosure rules. Disclosure Reports aggregate footprint data by business unit, facility, or reporting period. Audit Trail captures every data submission and approval for assurance purposes. Supplier Scorecards rate suppliers on their emissions intensity and sustainability commitments. Targets & Milestones track progress toward net zero goals (e.g., 50% reduction by 2030, net zero by 2040). The exam tests how to configure a disclosure report, how targets are defined and monitored, and what data flows into supplier scorecards.'),
    ('Data Collection & Integration',
     'NZC data can be entered manually, uploaded via CSV template, or integrated automatically from utility billing systems, travel management platforms, and ERP systems. Utility Data Connections (partnered utility providers) automate energy data ingestion. Data Quality indicators flag anomalies and missing data for review. Approval Workflows route submitted data through a validation and sign-off process before it is included in reports. MuleSoft and Salesforce Connect are common integration patterns for automating data flows from meters, building management systems, and fleet telematics. The exam tests how to configure a utility data connection, set up an approval workflow, and identify data quality issues in submitted footprint data.'),
    ('Goals, Targets & Climate Action Plans',
     'Organizations set emissions reduction targets in NZC at the company, business unit, or asset level. Science-Based Targets (SBTs) require alignment with the 1.5°C or well-below-2°C pathway defined by the SBTi. Baseline Year establishes the reference point for reduction measurement. Reduction Lever tracking records the planned and actual contribution of each initiative (renewable energy procurement, fleet electrification, building efficiency). Progress dashboards show attainment against targets over time. Recalculation logic adjusts baselines for acquisitions, divestitures, and methodology changes. The exam tests how to configure a Science-Based Target, how to link reduction levers to the target, and how recalculation policies affect historical data.'),
  ]),

  'order-management-admin-ap': kc_block('Order Management Admin AP: Key Concepts for the Exam', [
    ('Order Lifecycle & Order Summary',
     'Salesforce Order Management (SOM) tracks the post-purchase lifecycle from order capture through fulfillment and return. The Order Summary is the central object — it holds the canonical state of an order and aggregates Order Product Summaries (line items), Fulfillment Orders, Invoices, and Payment Summaries. Order states: Draft → Activated → Fulfilled → Cancelled. Order Product Summary states: Ordered → Allocated → Fulfilled → Returned. Change Orders handle post-capture modifications (address change, item cancellation, add-on). The AP exam tests the Order Summary data model, how state transitions are triggered, and the relationship between Order Summary and its child objects.'),
    ('Fulfillment & Inventory Allocation',
     'Fulfillment Orders represent the instruction to a fulfillment location to pick, pack, and ship items. Distributed Order Management (DOM) determines which fulfillment location handles each item based on inventory availability, proximity, and business rules. Fulfillment Location represents a warehouse, store, or 3PL partner. Inventory Availability is checked in real time via OCI (Omnichannel Inventory) API. Partial Fulfillment splits an order across multiple locations or shipments. Fulfillment Order Line Items map to specific order products and quantities. The exam tests how to configure fulfillment rules, how DOM selects locations, and how partial fulfillment is handled when one location has insufficient stock.'),
    ('Returns, Refunds & Return Merchandise Authorization',
     'Return Orders represent a customer&apos;s request to return one or more items. Return Merchandise Authorization (RMA) is the approval to accept a return. Return Order Line Items reference the original Order Product Summaries. Upon receipt of the returned item, a Return Receipt is created and inventory is restocked. Refunds are processed through the original payment method — partial refunds are supported. Credit Memos document the financial adjustment. Exchange workflows replace a returned item with a new one in a single transaction. The AP exam tests the configuration of a return policy, the sequence of return → receipt → refund → inventory restock, and how to set up an exchange flow.'),
    ('Pricing, Promotions & Tax',
     'Order Management uses Price Adjustments to apply discounts at the order level (coupon codes, loyalty discounts) or the line level (product-specific promotions). Price Book Entries set base prices. Tax Policies and Tax Treatments configure tax calculation — either Salesforce Tax or a third-party integration (Avalara, Vertex). Tax is calculated at order capture and re-calculated if the order is modified. Shipping Charges are added as a separate order product. The AP exam tests how to configure a promotion that applies a percentage discount to an entire order, how tax is recalculated on a change order, and how shipping charges are represented in the Order Summary data model.'),
    ('Integration & OCI (Omnichannel Inventory)',
     'OCI (Omnichannel Inventory) is the Salesforce API layer for real-time inventory availability checks across fulfillment locations. External systems (e-commerce platforms, ERP, WMS) integrate with SOM via the Order Management APIs. Webhooks and Platform Events notify external systems of order state changes. External Fulfillment Provider integration sends Fulfillment Orders to 3PL partners. The External Catalog and Pricing APIs support headless commerce scenarios where the storefront is not Salesforce B2B/B2C Commerce. The AP exam tests how to design the integration between a Salesforce-native Commerce Cloud storefront and SOM, how OCI responds to an availability check, and how to handle an external fulfillment partner that cannot receive Salesforce webhooks.'),
  ]),

  'order-management-developer-ap': kc_block('Order Management Developer AP: Key Concepts for the Exam', [
    ('OMS APIs & Customization',
     'Salesforce Order Management exposes a rich set of REST and Apex APIs for order lifecycle management. The `ConnectApi.OrderSummary` class provides Apex access to create, modify, and fulfill orders programmatically. REST APIs support headless integration for external storefronts. Key API operations: Create Order Summary, Adjust Order Product Summaries (price changes, cancellations), Create Fulfillment Order, Create Return Order, Ensure Funds (payment capture). Invocable Apex methods expose OMS operations to Flow and external callers. The developer exam tests how to write Apex that calls OMS Connect APIs, how to handle API exceptions, and how to expose a custom OMS operation as an Invocable Action.'),
    ('Order Orchestration with Flow',
     'OMS uses Salesforce Flow for order orchestration — automating the sequence of fulfillment, payment, notification, and return steps. Flow Orchestration (multi-stage orchestration) coordinates parallel and sequential work across teams and systems. Record-Triggered Flows respond to order state changes (e.g., when a Fulfillment Order is marked Fulfilled, trigger invoicing). Subflows modularize complex orchestration logic. Platform Events integrate OMS with external systems asynchronously — publish an event when an order state changes, subscribe in MuleSoft or an external ESB. The developer exam tests how to design an order orchestration flow, how to implement a re-try mechanism for failed API calls in a flow, and how to use Platform Events for async integration.'),
    ('Custom Fulfillment & External Integration',
     'External Fulfillment Providers receive Fulfillment Orders via outbound REST calls or Platform Events. The External Fulfillment Provider framework allows developers to register custom adapters that translate Salesforce Fulfillment Orders into 3PL-specific formats. Order callbacks update Salesforce when the 3PL ships or cancels — implemented as inbound REST endpoints in Salesforce (Experience Cloud, Salesforce Sites, or Functions). Error handling: when an external call fails, the flow must log the error, alert ops, and optionally retry. Idempotency keys prevent duplicate fulfillment on retry. The developer exam tests how to implement a custom fulfillment adapter, how to expose an inbound callback endpoint, and how to handle idempotent retries.'),
    ('Testing OMS Customizations',
     'Testing Order Management Apex requires creating test data for the full order hierarchy: Order Summary → Order Product Summary → Fulfillment Order → Fulfillment Order Line Item. OMS test utilities (ConnectApi mock classes) simulate API responses in test context. Use `Test.setMock(HttpCalloutMock.class, ...)` for external HTTP callouts. Test coverage must cover both happy path and error scenarios (insufficient inventory, payment failure, external system timeout). Integration tests against a Developer Edition or scratch org with OMS enabled validate end-to-end flows. The exam tests how to write a complete unit test for an OMS Apex method, how to mock OMS Connect API calls, and how to achieve >75% coverage on OMS trigger logic.'),
    ('Performance & Scalability Considerations',
     'High-volume order management requires careful attention to governor limits. Bulk order processing uses Apex Batch jobs rather than synchronous Apex. SOQL queries on Order Summary and child objects must use selective filters — add custom indexes on frequently queried fields (external order ID, status, created date). Platform Event subscriptions use CometD for streaming — design for at-least-once delivery and idempotent consumers. Large Return Order batches should be processed asynchronously to avoid CPU time limits. The OCI inventory check API has rate limits — design a caching layer for high-frequency availability checks. The developer exam tests how to design an OMS customization that handles 10,000+ daily orders without hitting governor limits.'),
  ]),

  'platform-foundations': kc_block('Salesforce Platform Foundations: Key Concepts for the Exam', [
    ('Salesforce Platform Architecture',
     'Salesforce is a multi-tenant cloud platform — all customers share the same infrastructure but data is logically isolated. The platform provides automatic upgrades (3 major releases per year: Spring, Summer, Winter), managed scalability, and built-in high availability. The metadata-driven architecture means that customizations (objects, fields, layouts, code) are stored as metadata rather than application code changes. The Lightning Platform delivers Force.com (declarative + code), Experience Cloud (portals), and Einstein (AI) on a common foundation. The Foundations exam tests understanding of the multi-tenant model, what the metadata layer controls, and how Salesforce manages upgrades without breaking customer customizations.'),
    ('Data Modeling Basics',
     'Salesforce organizes data into Objects (equivalent to database tables) and Records (rows). Standard Objects (Account, Contact, Lead, Opportunity, Case) are pre-built. Custom Objects store business-specific data. Fields define the data types stored in an object. Record Types allow different page layouts and picklist values per user group on the same object. Relationships connect objects: Lookup (loose coupling, optional parent), Master-Detail (tight coupling, cascade delete, roll-up summary). External Objects connect to external data via Salesforce Connect. The exam tests field type selection (Formula, Roll-Up Summary, Picklist, Text, Currency), when to use Lookup vs. Master-Detail, and how Record Types enable different business processes on the same object.'),
    ('Security Model Overview',
     'Salesforce security operates at four levels: Org (login, network access), Object (CRUD via profiles/permission sets), Field (read/edit via profiles/permission sets), and Record (OWD + Role Hierarchy + Sharing). Profiles assign baseline permissions to every user of a type. Permission Sets grant additional permissions to specific users without changing the profile. Permission Set Groups bundle multiple Permission Sets. Org-Wide Defaults (OWD) set the most restrictive baseline access for records. Role Hierarchy and Sharing Rules extend record visibility beyond OWD. The exam tests which security layer to modify to solve a given access problem — know that you always configure the most restrictive layer first, then open up selectively.'),
    ('Automation Overview: Declarative Tools',
     'Salesforce provides a suite of declarative automation tools. Validation Rules prevent records from being saved if data doesn&apos;t meet criteria — fires before save. Formula Fields calculate values automatically from other field values — read-only. Default Field Values pre-fill fields on new records. Record-Triggered Flows execute automation before or after a record save — replaces Process Builder and Workflow Rules. Approval Processes route records through human reviewers. Scheduled Flows process batches of records at a scheduled time. The Foundations exam tests which tool to use for: enforcing data quality (Validation Rule), calculating a derived value (Formula Field), automating a multi-step process (Flow), or requiring manager sign-off (Approval Process).'),
    ('AppExchange, Ecosystem & Trailhead',
     'AppExchange is Salesforce&apos;s marketplace for third-party applications, components, Flows, and Lightning Bolts. Managed Packages are ISV-published solutions that are upgradeable and have protected code. Unmanaged Packages are open-source and not upgradeable. Security Review ensures AppExchange listings meet Salesforce security standards. Partner Ecosystem includes consulting SIs, ISVs, and Salesforce-trained professionals (Trailblazers). Trailhead is the free learning platform — modules, trails, superbadges, and certifications. Trailblazer Community provides forums and user groups. The Foundations exam tests the difference between managed and unmanaged packages, how to evaluate an AppExchange listing, and the role of the Salesforce ecosystem in extending the platform.'),
  ]),

  'process-automation-ap': kc_block('Process Automation AP: Key Concepts for the Exam', [
    ('Flow Builder: Types & Trigger Contexts',
     'Flow Builder is the primary automation tool in Salesforce. Flow types: Record-Triggered (fires before/after save on record create/update/delete), Screen Flow (guided UI for users), Scheduled Flow (batch process at a set time), Autolaunched Flow (called programmatically, no UI). Before-Save flows are faster and can update the triggering record without a DML statement — cannot create/update other records. After-Save flows can create/update related records but run after the transaction. The AP exam tests deep Flow configuration: complex branching logic, loop handling, fault paths, and the performance differences between Before-Save and After-Save contexts.'),
    ('Advanced Flow Patterns',
     'Subflows allow one flow to call another — promotes reusability. Screen Flows can be embedded in Lightning pages, Experience Cloud sites, and utility bars. Dynamic Forms and Dynamic Actions in Lightning App Builder work alongside Screen Flows for fully conditional UI. Collection variables hold multiple records for batch operations within a flow. Loop elements iterate over collections. Decision elements branch based on conditions. Assignment elements modify variable values. Get Records / Create Records / Update Records / Delete Records elements perform DML. The exam tests how to design a flow that processes a collection of related records, handles errors gracefully, and uses a subflow to encapsulate a reusable business logic pattern.'),
    ('Approval Processes & Entitlements',
     'Approval Processes define multi-step human review workflows. Entry Criteria determine which records are eligible. Approver selection: specific user, queue, user field (manager), or related object field. Initial Submission Actions and Recall Actions run automatically when a record enters or exits the process. Step Actions run on approval or rejection at each step. Final Approval / Rejection Actions run at the end of the process. Delegated Approvers allow backups when the primary approver is unavailable. The AP exam tests how to configure a multi-step approval with parallel approvers, how to use dynamic approver assignment based on record fields, and how approval actions interact with other automation (Flows, email alerts).'),
    ('Triggered Automation: Apex Triggers',
     'When declarative automation is insufficient, Apex Triggers provide code-based automation. Triggers fire before/after insert, update, delete, and undelete events. Best practice: one trigger per object, all logic in a handler class (Trigger Handler pattern). Bulkification is mandatory — triggers must handle 200 records at once using collections instead of per-record DML or SOQL. Context variables: `Trigger.new`, `Trigger.old`, `Trigger.isInsert`, `Trigger.isBefore`. Recursion prevention: use a static Boolean flag to prevent triggers from re-firing. The AP exam tests how to design a bulkified trigger with a handler class, how to prevent recursion, and how to write test classes with sufficient bulk data.'),
    ('Testing, Debugging & Best Practices',
     'All Apex automation (triggers, classes) requires ≥75% code coverage for deployment to production. Test classes use `@isTest` annotation, `Test.startTest()` / `Test.stopTest()` to isolate governor limits, and `System.assert` for validation. Flow testing: use the Flow Debug feature in Flow Builder for step-through debugging; unit tests for flows via Apex use `Flow.Interview`. Process Automation audit trail: the Setup Audit Trail records configuration changes. Debug Logs capture detailed execution traces. Automation order of execution matters: Validation Rules → Before Triggers → Before Flows → After Triggers → After Flows → Workflow Rules → Processes → After-Save Flows. The exam tests how to diagnose an automation conflict and the correct sequence of execution.'),
  ]),

  'public-sector-solutions-ap': kc_block('Public Sector Solutions AP: Key Concepts for the Exam', [
    ('Case Management for Government',
     'Public Sector Solutions (PSS) extends Service Cloud for government constituent service. Cases represent constituent inquiries, complaints, or service requests. Case Classification uses a topic taxonomy to route and report on cases by type. Omni-Channel routes cases to the correct department or agent based on case type and priority. Knowledge Articles provide agents and constituents with self-service answers. Service Level Agreements (SLAs) via Entitlements enforce government response time mandates. Case Escalation Rules auto-escalate aging cases. The AP exam tests how to configure a government case management workflow, how to use knowledge for constituent self-service, and how to enforce compliance with response time SLAs.'),
    ('Licensing & Permitting',
     'PSS provides a pre-built Licensing and Permitting solution for government agencies. Business License Applications capture applicant information and supporting documents. Application Flows guide applicants through multi-step digital submission. Document Checklist Items define the required supporting documents. Inspection Tasks link to license applications for compliance verification. Renewal Workflows automate annual or periodic license renewals. Fee Structures define the application fees and payment integration. The exam tests how to configure a license application form, how document checklists are used in the review process, and how to set up renewal automation with payment collection.'),
    ('Grants Management',
     'PSS Grants Management supports the full grant lifecycle from solicitation to closeout. Funding Opportunities represent open grant competitions. Funding Award records track awarded grants including amount, period, and compliance requirements. Application review workflows route applications through scoring and approval. Budget Tracking monitors expenditures against awarded amounts. Progress Reports capture grantee performance data. Grantee portals (Experience Cloud) allow grantees to submit applications, reports, and amendment requests. The AP exam tests how to configure a grant application workflow, how budget tracking interacts with financial data, and how the grantee portal is provisioned.'),
    ('Inspections & Compliance',
     'Government inspections verify compliance with regulations — building permits, health codes, environmental standards. Inspection Visit records capture inspection dates, findings, and outcomes. Violations are documented with severity levels, corrective action requirements, and deadlines. Reinspection workflows schedule follow-up inspections when violations are found. Mobile inspection apps (Salesforce Field Service mobile or custom LWC) provide inspectors with offline access to inspection checklists and violation history. The AP exam tests how to configure an inspection workflow from scheduling through violation resolution, how mobile offline access works for inspectors, and how to generate compliance reports from inspection data.'),
    ('Constituent Engagement & Digital Experience',
     'PSS uses Experience Cloud to deliver government digital services to constituents — applying for licenses, reporting issues, tracking case status, and accessing benefits. Self-Registration allows new constituents to create accounts. Identity Verification can integrate with government ID systems or Knowledge-Based Authentication. Constituent Profiles aggregate all interactions (cases, licenses, permits, benefits) on a single constituent record. Einstein Bots deflect routine constituent inquiries before routing to agents. Accessibility (WCAG 2.1 AA compliance) is mandatory for government digital services. The AP exam tests how to configure a constituent self-service portal, how to enable case self-service, and how identity verification integrates with the portal registration flow.'),
  ]),

  'revenue-cloud-consultant': kc_block('Revenue Cloud Consultant: Key Concepts for the Exam', [
    ('CPQ Configuration & Product Rules',
     'Salesforce Revenue Cloud (CPQ + Billing) starts with product configuration. Product Features group options within a bundle. Configuration Attributes set product-level settings. Product Rules enforce valid configurations: Validation Rules (block invalid combos), Selection Rules (auto-add/remove products), Alert Rules (warn users), Filter Rules (hide irrelevant options). Option Constraints define which options are mutually exclusive or required together. Price Rules execute pricing logic at specific stages of the quote calculation. The consultant exam tests how to design a product bundle for a complex SaaS offering, which rule type handles a given scenario, and how to troubleshoot a rule that isn&apos;t firing as expected.'),
    ('Pricing, Discounting & Approvals',
     'CPQ pricing layers: List Price (Price Book) → Cost + Markup → Contracted Price → Block Pricing (volume tiers) → Percent of Total → Subscription Pricing. Discount Schedules define tier-based discounts. Price Waterfalls show how the final price is calculated step by step. Discount approval thresholds trigger Approval Processes when reps exceed authorized discount limits. Special Pricing Requests allow reps to request non-standard pricing from management. Quote-Level Discounts apply a single percentage across all lines. The consultant exam tests how to configure a tiered discount schedule, how price rules interact with manual discounts, and how approval thresholds are configured to route high-discount quotes.'),
    ('Subscription Billing & Contract Management',
     'CPQ Billing manages the billing lifecycle for subscription products. Products with a Subscription Type (Renewable, Evergreen) generate subscription records on order. Billing Frequency and Billing Timing settings determine when invoices are generated (in advance/in arrears). Contract Start/End Dates govern the subscription period. Contract Amendments handle upgrades, downgrades, and add-ons to in-force subscriptions — generating proration credit for the remaining contract period. Renewal Quotes are automatically generated before contract expiry. The consultant exam tests how to configure a subscription product for monthly billing, how proration is calculated on a mid-term amendment, and how renewal automation is configured.'),
    ('Revenue Recognition & ASC 606',
     'Revenue Cloud Revenue Recognition aligns with ASC 606 (IFRS 15) — revenue is recognized as performance obligations are satisfied. Revenue Schedules distribute invoice revenue across the service period. Recognition Methods: Ratable (even distribution over term), Event-Based (milestone-triggered), and one-time. Revenue Recognition Rules define the method for each product type. Finance Periods control accounting period boundaries. The Revenue Waterfall report shows deferred vs. recognized revenue by period. Adjustments and Credit Memos create correcting Revenue Recognition Transactions. The consultant exam tests how to configure revenue recognition for a scenario involving a mix of one-time professional services and recurring SaaS subscription revenue.'),
    ('Quote-to-Cash Integration & CPQ Object Model',
     'The CPQ data model: Quote → Quote Lines → Orders → Order Products → Contracts → Subscriptions → Assets. The Generate Order action converts a contracted quote into an Order. The Order Products generate Subscriptions (if configured). Billing picks up Order Products to generate Invoices. Contracts store the term, auto-renew settings, and list of subscription records. The Asset object tracks active products on an account for amendment and renewal. Integration with ERP: invoices and payment data flow to finance systems via API or MuleSoft. The consultant exam tests the full Quote-to-Cash flow, how to troubleshoot a quote that isn&apos;t generating the correct order, and how assets feed back into renewal quotes.'),
  ]),

  'sales-foundations': kc_block('Sales Foundations: Key Concepts for the Exam', [
    ('Salesforce Platform Basics for Sales',
     'The Sales Foundations certification validates fundamental Salesforce platform knowledge in a sales context. Key objects: Lead (unqualified prospect), Account (company or individual), Contact (person at an Account), Opportunity (potential deal), Activity (tasks and events). The Lead Conversion process creates an Account, Contact, and optionally an Opportunity in a single action — data from the Lead is mapped to the new records. Campaigns track marketing efforts and link to Leads and Contacts as Campaign Members. The exam tests basic navigation, record creation, activity logging, and the Lead-to-Opportunity conversion flow.'),
    ('Leads, Opportunities & Pipeline Management',
     'Lead Status (New → Working → Converted/Dead) tracks qualification progress. Lead Assignment Rules automatically route new leads to the right rep or queue based on criteria (geography, industry, source). Opportunity Stages reflect the sales process steps — tied to Probability % for forecasting. Close Date, Amount, and Stage drive the opportunity pipeline view. Opportunity Contact Roles define each contact&apos;s role in the deal (Decision Maker, Evaluator, Economic Buyer). Path provides stage guidance with key fields and coach notes at each stage. The exam tests how to configure lead assignment, how opportunity stages feed forecasting, and what Opportunity Contact Roles represent.'),
    ('Forecasting & Collaboration',
     'Collaborative Forecasting in Salesforce CRM aggregates rep-level opportunity data into manager and VP-level rollups. Forecast Types can be based on Opportunity Amount, Quantity, or a custom field. Forecast Categories (Pipeline, Best Case, Commit, Closed) reflect the rep&apos;s confidence level. Managers can adjust forecasts above or below their team&apos;s submitted amounts. Forecast quotas set individual targets. Chatter (collaboration feed) lets reps and managers discuss opportunities inline. Account Teams define which internal team members have access to an account and its opportunities. The exam tests how to read a collaborative forecast, how adjustments flow up the hierarchy, and what Forecast Categories mean.'),
    ('Productivity Tools: Email, Calendar & Mobile',
     'Salesforce Inbox integrates Outlook/Gmail with Salesforce — log emails to records, view related CRM data in the email client, and schedule meetings with calendar sync. Einstein Activity Capture automatically logs emails and calendar events to related Salesforce records, reducing manual data entry. Salesforce Mobile App lets reps access accounts, opportunities, and tasks on the go. Mobile Quick Actions (Log a Call, New Event) are customizable per object. Einstein Relationship Insights surfaces web and LinkedIn data about contacts and accounts. The exam tests how to configure Einstein Activity Capture, how email-to-case differs from email logging, and which productivity features are available on the mobile app without additional configuration.'),
    ('Reports, Dashboards & Sales Analytics',
     'Sales reports and dashboards provide visibility into pipeline health, quota attainment, and activity metrics. Key sales reports: Opportunities by Stage, Pipeline by Rep, Activities by Type, Lead Conversion Rate, Won/Lost Analysis. Summary reports group opportunities by stage or rep for subtotals. Matrix reports cross-reference rep by quarter for attainment tracking. Dashboards surface key metrics: Pipeline Value, Win Rate, Average Deal Size, Sales Cycle Length. CRM Analytics (Einstein Analytics) Sales Wave provides advanced pre-built dashboards. Report subscriptions deliver scheduled reports via email. The exam tests how to build a pipeline summary report, how to configure a dashboard for a VP of Sales, and how to share reports with the appropriate audience.'),
  ]),

  'technical-architect': kc_block('Salesforce Technical Architect (CTA): Key Concepts for the Exam', [
    ('Architecture Principles & Design Governance',
     'The Salesforce Certified Technical Architect (CTA) credential is the highest-level Salesforce certification. CTAs demonstrate mastery of designing end-to-end enterprise solutions across the full Salesforce platform and beyond. Core architecture principles: loose coupling, high cohesion, separation of concerns, idempotency, and graceful degradation. The Salesforce Well-Architected framework (Trusted, Easy, Adaptable) guides all design decisions. Architects document designs with ADRs (Architecture Decision Records), data flow diagrams, and integration sequence diagrams. The CTA exam — a Review Board scenario — tests the ability to justify every architectural decision under challenge, explain trade-offs, and adapt the design when the scenario changes mid-presentation.'),
    ('Integration Architecture at Scale',
     'Enterprise integration patterns for CTA: Request-Reply (synchronous REST/SOAP), Publish-Subscribe (Platform Events, Change Data Capture, Kafka), Batch (Bulk API, ETL jobs), and Event Streaming (CDC + MuleSoft). MuleSoft API-led connectivity is the standard recommendation for complex multi-system integrations. API Management (throttling, OAuth, versioning) is part of the design. Data consistency patterns: eventual consistency for async, distributed transaction patterns (Saga, Two-Phase Commit) for scenarios requiring atomicity. Governor limits (API daily limits, callout limits, event delivery limits) must be explicitly addressed in the architecture. The Review Board will challenge whether the proposed integration can handle peak load and failure scenarios.'),
    ('Data Architecture & Large Data Volumes',
     'Large Data Volume (LDV) design is a major CTA topic. Strategies: selective SOQL (always use indexed fields), skinny tables (pre-joined table maintained by Salesforce for performance), custom indexes on external IDs and frequently filtered fields, and Batch Apex for processing large data sets. Data archival moves aged records out of the main org to reduce query times. Data model normalization vs. denormalization trade-offs must be explicitly justified. Master Data Management prevents duplicates and maintains data quality at scale. External Objects (Salesforce Connect) keep high-volume external data out of Salesforce storage limits. The CTA must articulate specific LDV mitigations in the Review Board scenario.'),
    ('Security Architecture',
     'CTA-level security design covers: field-level encryption (Shield Platform Encryption) with trade-offs (deterministic vs. probabilistic encryption, search limitations), Customer-Managed Keys (BYOK), Event Monitoring for user behavior analytics, Field Audit Trail for long-term history, and Health Check/Security Center for org posture. Single Sign-On (SAML 2.0, OAuth 2.0 with JWT) integrates with enterprise identity providers (Okta, Azure AD). Connected App security: IP restrictions, OAuth scopes, certificate-based auth. Multi-Org security: data isolation between orgs in a multi-org strategy. The Review Board tests whether the security design meets compliance requirements (HIPAA, PCI, GDPR) without creating implementation or performance problems.'),
    ('Solution Architecture: Trade-offs & Justification',
     'The CTA Review Board is not a test of knowledge — it is a test of judgment. Every design decision must be justified with business context, technical constraints, and explicit trade-offs. Common scenarios: single org vs. multi-org strategy (data isolation vs. complexity), declarative vs. code (maintainability vs. flexibility), synchronous vs. asynchronous integration (consistency vs. availability), custom solution vs. AppExchange (speed to value vs. lock-in). Architects must anticipate failure modes: what happens when the integration endpoint is down? When the batch job fails at record 50,000? When a key customization hits a governor limit at scale? The Review Board rewards architects who proactively surface risks and design for resilience.'),
  ]),

  'technical-architect-evaluation': kc_block('CTA Evaluation: Key Concepts for Success', [
    ('Scenario-Based Assessment Format',
     'The Salesforce CTA (Certified Technical Architect) Review Board is a scenario-based oral examination — not a multiple-choice test. Candidates receive a multi-page business scenario 30 minutes before their 2-hour board session. The scenario describes a fictional company with a complex Salesforce + external system landscape, business requirements, and technical constraints. The candidate must design a complete solution architecture, present it to a panel of 3–4 CTA evaluators, and defend it under challenge. The evaluation tests architectural thinking, communication of trade-offs, adaptability when the scenario changes, and mastery of all Salesforce platform areas.'),
    ('Architecture Decision Justification',
     'Every architecture decision must be justified with three elements: the business requirement it satisfies, the technical reasoning (why this approach over alternatives), and the explicit trade-offs (cost, complexity, maintainability, risk). Evaluators specifically probe whether candidates can articulate why they chose X over Y — not just what they chose. Common decision areas: single org vs. multi-org, declarative vs. code, synchronous vs. async, AppExchange vs. custom build, Salesforce-native data store vs. external database. Preparation tip: for each major decision in practice scenarios, explicitly say "I chose X over Y because..." and name the specific trade-offs. Vague answers are probed until the candidate either justifies or concedes.'),
    ('Risk & Trade-off Analysis',
     'CTAs are expected to proactively identify risks in their own designs — evaluators expect candidates to say "One risk with this approach is..." before being asked. Risk categories: technical risks (governor limits, data volume, API capacity), business risks (adoption, change management, vendor lock-in), operational risks (monitoring, support, upgrades), and security/compliance risks. Mitigation strategies must be specific — not "we will monitor it" but "we will implement a dead letter queue with alerting and a manual reprocessing workflow for failed events." Risk scoring (probability × impact) demonstrates mature architectural thinking. The evaluation rewards candidates who are intellectually honest about their design&apos;s weaknesses.'),
    ('Defense of Design Choices',
     'The Review Board will challenge design choices with "What if..." and "Why not..." questions to test whether the candidate truly understands the solution or memorized a template. Common challenges: "What if the integration endpoint goes down for 4 hours during business hours?", "What if your MuleSoft solution is over budget — what is the fallback?", "Why didn&apos;t you use a Platform Event here instead of a REST callout?" Candidates should respond with: acknowledge the challenge, explain the impact on the current design, and either defend it (with new justification) or adapt it (with a revised approach). Changing a design under challenge is not failure — it demonstrates that the architect can think dynamically.'),
    ('Evaluator Rubric & Common Failure Areas',
     'The CTA Review Board evaluates candidates on: Breadth (covering all required architecture areas), Depth (detailed, specific answers in each area), Communication (clear diagrams, structured verbal explanations), and Adaptability (handling scenario changes and challenges gracefully). Common failure areas: (1) Focusing only on Salesforce and ignoring external systems. (2) Providing generic answers without specific Salesforce feature references. (3) Failing to address security, data architecture, or integration explicitly. (4) Reacting defensively to challenges instead of engaging constructively. (5) Running out of time before covering all scenario requirements. Preparation: complete 10+ full mock Review Board sessions with peer CTAs or coaches, record and review yourself, and practice under time pressure.'),
  ]),

  'technical-architect-review-board': kc_block('CTA Review Board: Key Concepts for Preparation', [
    ('Review Board Format & Logistics',
     'The Salesforce CTA Review Board is a 2-hour oral examination conducted virtually (via Zoom) before a panel of 3–4 currently active Salesforce CTAs who serve as evaluators. Candidates receive the scenario document 30 minutes before the session starts — use this time to read carefully, identify all requirements (functional and non-functional), spot constraints, and outline a response structure. The session consists of a ~30-minute presentation (with shared screen for diagrams) followed by ~60–90 minutes of Q&A and probing challenges. A whiteboard tool (or pre-prepared diagrams) is expected. Candidates are scored Pass or Fail with detailed feedback provided regardless of outcome.'),
    ('Preparing Architecture Diagrams',
     'Effective CTA presentations use clear, well-labeled diagrams: Context Diagram (systems involved and their relationships), Integration Architecture Diagram (data flows, protocols, sync/async), Data Model Diagram (key objects, relationships, volumes), Security Architecture Diagram (identity, encryption, sharing), and Deployment Diagram (orgs, sandboxes, CI/CD). Diagrams must be legible when screen-shared — use color coding by system type (Salesforce = blue, external = gray, integration layer = orange). Each diagram should have a legend. Practice presenting each diagram in under 90 seconds with a clear narrative: "This shows... The key decision here is... The trade-off is...". Avoid cluttered diagrams that require extensive explanation.'),
    ('Common Failure Areas & How to Avoid Them',
     'Statistical analysis of failed Review Board attempts reveals recurring gaps: (1) Incomplete solution — not addressing all scenario requirements; use a checklist before presenting. (2) Lack of specificity — saying "we will use Salesforce&apos;s security model" without specifying OWD, role hierarchy, sharing rules, or Shield. (3) Ignoring non-functional requirements — scalability, performance, availability, compliance. (4) No integration error handling — every integration must address what happens when it fails. (5) Defensive responses to challenges — treat every challenge as a "help me understand" question, not an attack. (6) Time management — running over on presentation leaves no time for Q&A, which is where most probing happens. Practice with a timer religiously.'),
    ('Responding to Board Challenges',
     'When a Board member challenges your design, use the STAR-A framework: Situation (restate the challenge to show you understood), Think (pause visibly — evaluators want to see you think, not react), Answer (address the specific challenge with a specific answer), Rationale (explain the reasoning), Adapt (if the challenge reveals a genuine gap, update your design on the spot and explain the revision). Never say "I don&apos;t know" — say "My initial design assumed X; given your challenge, I would revise it to Y because..." The Board is not trying to trick you — they are stress-testing your design for production-level robustness. Candidates who engage thoughtfully with challenges often score higher than those whose initial designs were unchallenged.'),
    ('Success Strategies & Preparation Plan',
     'Successful CTA candidates typically follow a 3–6 month structured preparation plan: (1) CTA Bootcamp or coaching program with active CTAs. (2) Weekly mock Review Board sessions — at minimum 8–10 full mock sessions before attempting the real board. (3) Deep-dive study in weak areas: large data volumes, integration architecture, security, and multi-org strategy are the most commonly cited gaps. (4) Build a library of 5–10 practice scenarios (Salesforce provides some; community resources provide more) and practice presenting each. (5) Get comfortable diagramming under time pressure — set a timer for 20 minutes and draw a complete architecture diagram from a scenario. (6) Join the CTA Study Group in the Trailblazer Community for peer feedback and shared resources.'),
  ]),
}

def insert_key_concepts(slug, kc_html):
    path = os.path.join(BASE, slug, 'page.tsx')
    if not os.path.exists(path):
        print(f"SKIP (not found): {slug}")
        return
    content = open(path, encoding='utf-8').read()
    if 'id="key-concepts"' in content:
        print(f"SKIP (already has KCs): {slug}")
        return
    target = '          <div id="practice-questions"'
    if target not in content:
        target = '            <div id="practice-questions"'
    if target not in content:
        print(f"WARN: could not find practice-questions div in {slug}")
        return
    content = content.replace(target, kc_html + target, 1)
    content = re.sub(
        r"(\{ id: 'practice-questions', title: '[^']+' \})",
        "{ id: 'key-concepts', title: 'Key Concepts' },\n              \\1",
        content, count=1
    )
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  OK: {slug}")

print("Batch 3: processing pages...")
for slug, html in PAGES.items():
    insert_key_concepts(slug, html)
print("Done.")
