#!/usr/bin/env python3
"""Add Key Concepts sections to missing cert pages — batch 2 (contact-center-ap through mulesoft-integration-foundations)."""
import os, re

BASE = '/Users/brahmajikatragadda/Downloads/salesforce-certifications/src/app/certifications'

def kc_block(title, concepts):
    items = ''
    for h, b in concepts:
        items += f'''              <div>
                <p className="font-semibold text-gray-900 mb-1">{h}</p>
                <p>{b}</p>
              </div>\n'''
    return f'''
          {{/* Key Concepts */}}
          <div id="key-concepts" className="mt-12 rounded-xl border border-gray-100 bg-white p-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">{title}</h2>
            <div className="space-y-4 text-sm text-gray-700">
{items}            </div>
          </div>
'''

PAGES = {
  'contact-center-ap': kc_block('Contact Center AP: Key Concepts for the Exam', [
    ('Omni-Channel Routing & Queues',
     'Omni-Channel routes work items (Cases, Chats, Calls) to the most appropriate available agent. Routing Configurations define how work is prioritized and assigned — by queue capacity, agent skill, or least-active. Presence Configurations control which channels an agent can handle simultaneously and their capacity. Service Channels map Salesforce objects (Case, Chat Session, Voice Call) to the routing engine. Queues hold work items pending assignment. The AP exam tests how to configure Omni-Channel for a scenario with multiple channels (voice, chat, email) and mixed-skill agents — know how capacity units work and how to prevent agent overload.'),
    ('Service Cloud Voice & CTI Integration',
     'Service Cloud Voice (SCV) embeds telephony directly into the agent console. Amazon Connect is the native telephony partner, but any BYOT (Bring Your Own Telephony) partner can integrate via the SCV API. Real-Time Transcription captures call text live, enabling Einstein recommendations to surface knowledge articles mid-call. Call Controls (mute, hold, transfer, conference) appear in the Omni-Channel widget. After-call work status prevents new work from routing during wrap-up. CTI (Computer Telephony Integration) via Open CTI embeds third-party phone systems using a JavaScript framework. The exam tests SCV configuration, how transcription data is stored, and how to configure after-call work.'),
    ('Einstein Bots & Digital Engagement',
     'Einstein Bots handle routine customer inquiries via chat before escalating to a human agent. Bot Dialogs define conversation flows — intents, entities, and slot-filling collect required information. Bot versions support staged rollout. Einstein Bot Builder uses a visual conversation designer. Escalation from bot to agent preserves conversation context and transcript. Digital Engagement channels: Chat (embedded web), Messaging (SMS, WhatsApp, Facebook Messenger), and Email. Each channel has its own routing configuration. Enhanced Bot (built on Einstein AI) supports more complex NLU. The exam tests how to configure a bot, define intents, and set up escalation routing.'),
    ('Knowledge Management & Deflection',
     'Salesforce Knowledge articles provide agents and customers with searchable help content. Article Types define the structure (field layout) of different content categories. Data Categories control visibility — agents may see all, customers only see published public articles. Einstein Search Suggestions surfaces relevant articles based on case subject and description. Lightning Knowledge uses a unified Article object. Channels: Internal (agent console), Customer (self-service portal), Partner (partner community). Article Usage Metrics track deflection rate. Knowledge Base feeds Einstein Bots and Einstein Article Recommendations. The exam tests Knowledge configuration, how data categories restrict visibility, and how to measure deflection effectiveness.'),
    ('Reporting & Contact Center Analytics',
     'Contact center KPIs: Average Handle Time (AHT), First Contact Resolution (FCR), Customer Satisfaction (CSAT), Queue Wait Time, Abandonment Rate. Omni-Channel Supervisor provides a real-time view of agent availability, queue depth, and work item status. Historical reporting uses standard Salesforce reports on Case, Voice Call, and Chat Transcript objects. CRM Analytics Contact Center apps provide pre-built dashboards. Escalation analysis identifies bot-to-human handoff patterns. The AP exam tests how to configure Omni-Channel Supervisor views, which standard report objects contain which metrics, and how to set up a CSAT survey triggered after case closure.'),
  ]),

  'cpq-billing-ap': kc_block('CPQ Billing AP: Key Concepts for the Exam', [
    ('Quote-to-Cash Process & Billing Setup',
     'CPQ Billing extends Salesforce CPQ to handle the full Quote-to-Cash cycle: Quote → Order → Contract → Invoice → Payment. Billing must be enabled in CPQ Settings. The Order object bridges CPQ and Billing — when a Quote is contracted, an Order is created, and Billing creates invoices from Order Products. Billing Policies define the invoice generation schedule, payment terms, and invoice consolidation rules. Legal Entities represent the billing entities within a company — important for multi-national deployments. Tax Integration (Avalara, Vertex) calculates tax on invoices. The AP exam tests the configuration sequence for a new Billing setup and the object relationships in Quote-to-Cash.'),
    ('Invoice Generation & Billing Rules',
     'Invoices are generated from Order Products based on Billing Rules — which define when and how charges are billed. Bill Now generates an invoice immediately. Bill in Advance bills at the start of a period. Bill in Arrears bills at the end of a period. Billing Frequency options: Monthly, Quarterly, Annually, or one-time. Invoice Run triggers invoice generation for all eligible Order Products. Invoice Lines represent individual charges. Credit Notes handle adjustments and cancellations. Billing Batches process large volumes asynchronously. The exam tests how to configure billing rules for common scenarios (annual subscription billed monthly, one-time setup fee billed immediately with first invoice).'),
    ('Usage-Based Billing',
     'Usage Billing handles variable charges based on consumption — API calls, data transfer, seat count. Usage Summaries aggregate raw usage data into billable amounts for an invoice period. Usage Rate Cards define the price per unit or tier. Rated Usage is the calculated charge ready for invoicing. Usage data can be imported via CSV, API, or custom integration. Overage billing charges usage above the included amount in a subscription. The AP exam tests how to configure usage billing for a SaaS scenario (base subscription + overage), how usage summaries feed invoice lines, and how to test the billing calculation with sample usage data.'),
    ('Payment Processing & Dunning',
     'Payment Gateways in CPQ Billing connect to payment processors (Stripe, CyberSource, Adyen) to tokenize and charge payment methods. Payment Terms define when payment is due after invoice generation (Net 30, Due on Receipt). Auto-Pay automatically charges the stored payment method on the invoice due date. Dunning Processes handle failed payments — automated retry schedules, dunning emails, and account holds after N failed attempts. Payment Allocations apply payments to specific invoices. Refunds and Credit Memos reverse billed charges. The exam tests how to configure auto-pay, design a dunning workflow, and handle the scenario where a payment fails and needs to be retried.'),
    ('Revenue Recognition & Reporting',
     'Revenue Recognition in CPQ Billing aligns with ASC 606 and IFRS 15 standards. Revenue Schedules distribute invoice revenue across the service period rather than recognizing it all at invoice date. Revenue Recognition Rules define when revenue is recognized (ratably over subscription term, point-in-time for one-time charges). Revenue Distribution Transactions record the recognized amounts per period. Finance Period controls define accounting period boundaries. Revenue Reporting surfaces recognized vs. deferred revenue. The exam tests how to configure revenue recognition for a subscription scenario, how to handle amendments that modify in-period revenue schedules, and key reporting objects.'),
  ]),

  'crm-analytics-einstein-discovery-consultant': kc_block('CRM Analytics & Einstein Discovery: Key Concepts for the Exam', [
    ('Data Architecture: Datasets & Dataflows',
     'CRM Analytics (formerly Tableau CRM / Einstein Analytics) stores data in Datasets — optimized columnar data stores separate from the Salesforce database. Dataflows define how data is extracted from Salesforce objects, joined, aggregated, and loaded into datasets — using a JSON-based recipe. Recipes (Data Prep) provide a visual ETL interface for data transformation. External data can be loaded via CSV upload or connected datasets. Incremental sync keeps datasets fresh with only changed records. The consultant exam tests how to design a dataflow for a multi-object scenario (e.g., joining Accounts, Opportunities, and Cases), how to configure incremental sync, and how to troubleshoot failed dataflow jobs.'),
    ('Lenses, Dashboards & Stories',
     'Lenses are explorations of a single dataset — ad-hoc visual analysis. Dashboards assemble multiple charts, tables, and filters into a unified analytical experience. Dashboard JSON defines the full layout and query logic — consultants must be able to read and modify dashboard JSON for advanced customization. SAQL (Salesforce Analytics Query Language) powers advanced queries that the UI cannot express. Binding formulas connect filters and widgets — selection in one widget filters another. Stories are AI-generated narratives that explain key drivers in a dataset. The exam tests how to build a dashboard, use bindings for interactive filtering, and write basic SAQL for a custom query.'),
    ('Einstein Discovery Insights & Models',
     'Einstein Discovery uses statistical machine learning to find patterns in historical data and generate predictive insights. Stories analyze a dataset and identify the top factors that influence a chosen outcome metric. Predictions deploy a Story as a scoring model — each Salesforce record gets a predicted score. Writeback deploys predictions back to Salesforce fields (e.g., Opportunity Win Probability). Improvement Suggestions recommend actions that increase the probability of a positive outcome. Model refresh keeps predictions current as new data accumulates. The consultant exam tests how to create a Story for a business scenario, interpret the top predictors, and configure writeback to update opportunity or case fields.'),
    ('Security: Row-Level & Field-Level Access',
     'CRM Analytics uses a separate security model from Salesforce record sharing. Dataset Security Predicates filter rows based on the logged-in user — referencing user fields like role, profile, or a custom attribute. Inheritance mode automatically applies Salesforce sharing rules to the dataset. User Attributes defined in CRM Analytics can be used in predicates and SAQL. Field-level security hides specific columns from certain users or groups. App sharing (Viewer, Editor, Manager) controls who can access and modify dashboards. The exam tests how to design a security predicate for a hierarchical visibility scenario (managers see their team&apos;s data, reps see only their own).'),
    ('Deployment, Administration & Integration',
     'CRM Analytics apps are deployed using packages (change sets or CLI). Template Apps provide pre-built analytics solutions for Sales, Service, and specific industries. Custom apps extend or replace template apps. Connected objects define the Salesforce data sources for a template app — configuring which objects and fields feed each dataset. Scheduled dataflow runs keep datasets refreshed (up to 24 scheduled runs per day). Admin setup includes enabling CRM Analytics, assigning permission sets, and configuring connected objects. Integration with Einstein Discovery requires a CRM Analytics Plus license. The exam tests deployment sequences, template app configuration, and troubleshooting scheduling and data refresh issues.'),
  ]),

  'email-specialist-practice-test': kc_block('Email Specialist Practice Test: Key Concepts to Review', [
    ('Email Delivery, Compliance & Subscriber Management',
     'CAN-SPAM requires a physical mailing address, an unsubscribe mechanism honored within 10 days, and honest subject lines. GDPR requires explicit opt-in consent for EU subscribers and the right to erasure. CASL applies to Canadian recipients. Suppression Lists (global unsubscribes, bounces, complaints) prevent sending to opted-out addresses. Data Extensions store subscriber data with custom attributes for segmentation. Subscriber keys uniquely identify a contact across channels. Double opt-in sends a confirmation email before adding a subscriber to a sendable list. The practice exam frequently tests which compliance rule applies to a given scenario and how suppression lists interact with send classification.'),
    ('Journey Builder & Triggered Sends',
     'Journey Builder orchestrates multi-step, multi-channel customer journeys. Entry Sources include Data Extensions (scheduled batch entry), API Events (real-time triggered entry), Salesforce Data (CRM object record changes), and CloudPages forms. Activities include Email Send, SMS, Push, Wait, Decision Split (conditions), Engagement Split (opens/clicks), Einstein STO (Send Time Optimization), and Update Contact. Journey goals and exit criteria control when a contact completes or leaves the journey. Triggered Sends are simpler, single-email automation — good for transactional emails (order confirmations, password resets). The exam tests which journey activity to use for a given scenario and how entry source options differ.'),
    ('Content Builder & Personalization',
     'Content Builder is the centralized asset library for emails, templates, images, and documents. Email templates use drag-and-drop blocks or HTML with AMPscript or SSJS for dynamic content. AMPscript is the scripting language for personalization — `%%[VAR %%]` syntax, `Lookup()` retrieves data extension values, `IF/THEN/ENDIF` for conditional content. Dynamic Content blocks show different content to different subscribers based on rules. Personalization Strings insert subscriber attributes inline. Content Syndication shares blocks across business units. The exam tests how to write an AMPscript snippet that retrieves a value from a data extension and conditionally displays content.'),
    ('Send Classifications & Deliverability',
     'Send Classifications define the unsubscribe behavior for a send: Commercial (subscriber can unsubscribe), Transactional (not subject to commercial opt-out rules). Sender Profiles, Delivery Profiles, and Send Classifications combine to control From address, reply-to, and unsubscribe handling. IP Warming is required when using a new dedicated IP — gradually increase send volume to build sender reputation. SPF, DKIM, and DMARC records authenticate sending domains and improve deliverability. Bounce handling: Soft Bounces (temporary, retry) vs. Hard Bounces (permanent, suppress). Spam complaints trigger suppression and affect sender reputation. The exam tests how to configure send classifications for a mixed transactional/commercial sender.'),
    ('Analytics & Reporting',
     'Marketing Cloud Email reporting tracks: Sent, Delivered, Opens (unique + total), Clicks (unique + total), Bounces (hard + soft), Unsubscribes, and Spam Complaints. Click Rate = Clicks / Delivered. Open Rate = Opens / Delivered. The Tracking workspace in Email Studio shows send-level metrics. Data Views (hidden data extensions: _Sent, _Open, _Click, _Bounce, _Unsubscribe) allow SQL queries in Automation Studio for custom reporting. Einstein Engagement Scoring predicts which subscribers are likely to engage. Send Throttling limits the number of emails sent per hour to protect deliverability. The exam tests how to calculate email KPIs from raw numbers and which reporting tool to use for a given analysis need.'),
  ]),

  'heroku-architect': kc_block('Heroku Architect: Key Concepts for the Exam', [
    ('Heroku Platform Architecture & Dynos',
     'Heroku runs applications in lightweight Linux containers called Dynos. Dyno types: Web (handles HTTP traffic), Worker (background jobs, no HTTP), One-Off (manual or scheduled tasks). Dyno sizes range from Eco (shared, sleeps after 30 min) to Performance-XL (dedicated, high memory). The Dyno Manager restarts crashed dynos automatically. Horizontal scaling adds more dynos of the same type; vertical scaling changes the dyno size. The Procfile defines process types and start commands. The Router load-balances requests across web dynos (round-robin with session stickiness disabled by default). The architect exam tests how to size and scale a Heroku deployment for a given traffic and processing profile.'),
    ('Data Services: Heroku Postgres & Redis',
     'Heroku Postgres is the primary managed database — available in Essential (row limits), Standard, Premium, and Private tiers. Connection pooling via PgBouncer reduces database connection overhead. Follow databases provide read replicas for analytics queries. Continuous protection (WAL archiving) enables point-in-time recovery. Heroku Data for Redis handles caching, session storage, and pub/sub messaging. Redis plans: Mini (non-persistent) to Premium (persistent, HA). Heroku Key-Value Store (Redis) replaces legacy Heroku Redis. The exam tests data tier selection for a given durability, availability, and performance requirement, and how to configure read replicas for a high-read workload.'),
    ('CI/CD, Review Apps & Release Management',
     'Heroku Pipelines define promotion stages: Development → Staging → Production. Review Apps automatically deploy pull requests to ephemeral apps for testing — each PR gets its own URL. Heroku CI runs automated tests on each push and blocks promotion on failure. The `heroku pipelines:promote` command promotes a slug (compiled app image) from one stage to the next without rebuilding. Release Phase runs migration scripts or data seeding commands before each new release goes live. Rollbacks revert to a previous release slug instantly. Config Vars (environment variables) are separate per stage, preventing accidental production config in staging. The exam tests how to design a pipeline for a team with multiple parallel feature branches.'),
    ('Security, Compliance & Private Spaces',
     'Heroku Private Spaces run Dynos and data services inside a dedicated, isolated network environment — required for compliance workloads (HIPAA, PCI, SOC 2). Private Spaces connect to Salesforce orgs via Salesforce Private Connect (AWS PrivateLink) for secure data exchange without traffic traversing the public internet. Internal Routing restricts apps in a Private Space to only receive traffic from within the space. Shield Private Spaces add encryption at rest and enhanced security controls. Log Drains export Heroku logs to external SIEM or logging systems. Heroku Enterprise provides SSO, audit logs, and team-based access controls. The exam tests Private Space configuration for compliance scenarios and the networking model.'),
    ('Architecture Patterns for Salesforce + Heroku',
     'Heroku Connect syncs data bidirectionally between Heroku Postgres and Salesforce objects — enabling Heroku apps to read/write Salesforce data without direct API calls. Write acceleration pattern: high-volume writes go to Heroku Postgres first, then Heroku Connect syncs to Salesforce asynchronously, avoiding API rate limits. Event-driven pattern: Salesforce Platform Events trigger Heroku workers via Heroku Connect CDC. Compute-offload pattern: complex calculations (ML inference, image processing) run on Heroku and results are written back to Salesforce. The architect exam tests which pattern to apply for a given scalability, latency, and Salesforce API limit scenario — especially for IoT, mobile, or high-volume data scenarios.'),
  ]),

  'heroku-developer-ap': kc_block('Heroku Developer AP: Key Concepts for the Exam', [
    ('Buildpacks, Runtime & Procfile',
     'Heroku detects the language/framework of an app using Buildpacks — Node.js, Python, Ruby, Java, Go, and more are officially supported. Custom Buildpacks extend the detection and build process. The build process: push code → detect buildpack → compile → create slug → deploy to dynos. The Procfile defines process types: `web: node server.js` (HTTP), `worker: node worker.js` (background). Multiple process types can run simultaneously. Eco and Basic dynos sleep after inactivity. The `heroku local` command runs the Procfile locally using `.env` for config vars. The AP exam tests how to configure a Procfile for a multi-process app and how to debug a build failure using build logs.'),
    ('Config Vars, Add-ons & Environment Management',
     'Config Vars are environment variables set per Heroku app — accessible in code as `process.env.VAR_NAME`. Never hardcode secrets; always use Config Vars. Add-ons extend Heroku apps with third-party services (databases, email, monitoring, logging) — provisioned via `heroku addons:create`. Each add-on sets Config Vars automatically (e.g., DATABASE_URL for Postgres). Add-on plans scale independently from app dynos. The Heroku CLI (`heroku config:set`, `heroku addons`) manages Config Vars and Add-ons. The AP exam tests how to pass secrets to a Heroku app securely, how to provision and configure an add-on, and how to rotate credentials without downtime.'),
    ('Heroku Connect & Salesforce Integration',
     'Heroku Connect maps Salesforce object records to Heroku Postgres tables, syncing data bidirectionally on a configurable schedule. Setup: provision Heroku Connect add-on → authenticate with Salesforce → create mappings (object, fields, direction). Read mappings pull Salesforce data to Postgres. Write mappings push Postgres changes back to Salesforce. Conflict detection handles records modified in both systems simultaneously. The `_hc_lastop`, `_hc_err`, and `isdeleted` system columns track sync status. Connection limits on Salesforce API calls govern sync frequency. The AP exam tests how to configure a Heroku Connect mapping, troubleshoot sync errors, and design for high-volume bidirectional sync within Salesforce API limits.'),
    ('Async Jobs, Workers & Message Queues',
     'Background processing on Heroku uses Worker dynos. Job queues (Redis-backed: Bull, Bee-Queue for Node.js; Celery for Python; Sidekiq for Ruby) decouple work submission from processing. Pattern: web dyno enqueues a job → worker dyno processes it asynchronously. This prevents long-running tasks from blocking HTTP responses and allows independent scaling of web vs. worker processes. Scheduled tasks use Heroku Scheduler add-on (cron-like) or clock processes in the Procfile. Dead Letter Queues capture failed jobs for retry or investigation. The exam tests how to architect a job queue for a given throughput requirement and how to handle job failures gracefully.'),
    ('Monitoring, Logging & Performance',
     'Heroku Logplex aggregates logs from all Dynos, Router, and add-ons into a unified stream — `heroku logs --tail` for real-time viewing. Log Drains forward logs to external services (Papertrail, Datadog, Splunk). Application metrics (response time, throughput, error rate) are visible in the Heroku Dashboard. Dyno metrics show CPU and memory usage — memory leaks cause R14 (memory quota exceeded) errors. R10 (Boot timeout), H10 (App crashed), H12 (Request timeout at 30s) are common Heroku error codes. New Relic, Scout APM, and Datadog add-ons provide application performance monitoring. The exam tests how to diagnose a performance problem using logs and metrics, and how to configure alerting for dyno errors.'),
  ]),

  'industries-cpq-developer': kc_block('Industries CPQ Developer: Key Concepts for the Exam', [
    ('Product Catalog & Configuration',
     'Industries CPQ (formerly Vlocity CPQ) uses a TM Forum-aligned product catalog. Product Specifications define the attributes and structure of a product. Product Offerings are the sellable versions with pricing. Product Bundles group related offerings (e.g., a broadband + voice + TV bundle). Attributes define configurable options — data cap, contract term, device color. Configuration Rules enforce valid attribute combinations and auto-set dependent attributes. Context Rules make product availability conditional on account type, geography, or existing products. The developer exam tests how to configure attribute rules, implement context rules in declarative logic, and extend configuration behavior with custom Apex when rules are insufficient.'),
    ('Pricing Rules & Calculation Framework',
     'Pricing in Industries CPQ uses a layered calculation framework. Price Lists define base prices for products and attributes. Pricing Procedures define the sequence of pricing steps — list price → adjustments → promotions → taxes → total. Pricing Elements are individual steps in the procedure (e.g., apply 10% loyalty discount). Pricing Variables store intermediate calculation results. Custom Pricing Apex classes implement complex pricing logic not achievable declaratively. Price Waterfall shows the full breakdown of how the final price was calculated. The developer exam tests how to implement a custom pricing step, how to debug a price calculation using the price waterfall, and how pricing procedures interact with multi-product bundles.'),
    ('Quote & Order Lifecycle',
     'The Industries CPQ quote lifecycle: Product Selection → Configuration → Pricing → Quote → Order → Fulfillment. Decomposition breaks complex bundled products into fulfillable line items for downstream provisioning systems. Order Items map to fulfillment line items with action codes (Add, Change, Remove, Suspend). Contract integration manages subscription amendments — when a customer changes an in-force service, a Change Order is created with the correct action codes. Quote versioning supports multiple concurrent scenarios. The developer exam tests the decomposition logic, how to configure action codes for amendments, and how to implement custom validation before order submission.'),
    ('Integration & API Patterns',
     'Industries CPQ exposes REST APIs for catalog queries, configuration, pricing, and order submission. The CPQ API is used by external systems (self-service portals, partner tools) to perform quoting and ordering programmatically. Asset-Based Ordering (ABO) APIs query existing customer assets to determine available change operations. Integration with OSS/BSS systems (provisioning, billing) uses the fulfillment API to push decomposed order items. The developer exam tests the correct API endpoint for a given operation, how to authenticate and call the CPQ API from an external system, and how to handle API error responses for failed configuration or pricing requests.'),
    ('Customization: Apex, LWC & OmniStudio',
     'Industries CPQ customization uses: Custom Apex for complex business logic (configuration rules, pricing steps, order validation), LWC components for custom UI within the CPQ cart or checkout, and OmniStudio (FlexCards, OmniScripts) for guided selling experiences. Integration Procedures (OmniStudio) handle multi-step API orchestration. DataRaptors transform data between Salesforce and external systems within CPQ flows. The developer exam tests which customization tool to use for a given requirement — declarative rules first, Apex for complex logic, LWC for custom UI, and OmniStudio for guided workflows. Know the OmniStudio activation sequence: DataRaptor → Integration Procedure → OmniScript.'),
  ]),

  'loyalty-management-ap': kc_block('Loyalty Management AP: Key Concepts for the Exam', [
    ('Program Design: Tiers & Points',
     'Salesforce Loyalty Management structures programs around a Loyalty Program with one or more Tiers (e.g., Silver, Gold, Platinum) and a Currency (points, miles, cashback). Tier Groups define the criteria for tier qualification — spending thresholds, visit counts, or points earned. Tier Period determines how long earned status lasts and when it resets (anniversary, calendar year). The Loyalty Member object tracks each enrolled customer&apos;s current tier, points balance, and program history. Qualifying vs. Non-Qualifying Points: qualifying points count toward tier status; non-qualifying points are bonus awards that don&apos;t affect tier. The AP exam tests how to configure a tier structure with custom qualification rules and how tier periods interact with reset logic.'),
    ('Points Accrual & Redemption Rules',
     'Accrual Rules define how members earn points — by transaction amount, product category, channel, or event. Accrual Rate can be a fixed amount or a percentage of spend. Partner Accruals allow members to earn points at non-Salesforce partner businesses via API. Redemption Rules define how points are spent — minimum redemption threshold, redemption value (100 points = $1), and eligible products. Vouchers are generated upon redemption and tracked as Loyalty Vouchers. Point Expiry Rules define when dormant points expire and send pre-expiry notifications. The exam tests how to configure an accrual rule for a partner scenario, how to set a redemption rule with a minimum threshold, and how expiry notifications are triggered.'),
    ('Promotions & Member Engagement',
     'Loyalty Promotions offer bonus points or tier benefits for specific activities during a promotional period. Promotion Eligibility Rules restrict which members can participate (by tier, segment, or geography). Benefit Types include points multipliers, free products, and discount vouchers. Promotions are linked to a Loyalty Program and activated for a date range. Member Engagement events (birthday, milestone, referral) trigger automatic point awards or benefit grants. Engagement Attributes store program-specific data on the member profile. The exam tests how to configure a time-limited promotion with eligibility rules, how to award bonus points for a lifecycle event, and how to use member attributes to personalize promotions.'),
    ('Partner Integration & Ecosystem',
     'Loyalty programs often partner with airlines, hotels, retailers, and financial services to allow cross-brand earning and redemption. Partner Accounts represent participating businesses in Salesforce. Partner Accrual/Redemption endpoints expose REST APIs that partners call to post transactions. Loyalty Connect provides a pre-built API gateway for partner integrations. Transaction Journals record every point earn and burn event with full audit trail. The AP exam tests how to configure a partner-facing API for an earn scenario, how transactions are posted and validated, and how to design the security model so that a partner can only post transactions for their own members.'),
    ('Analytics & Program Reporting',
     'Key Loyalty KPIs: Active Member Rate, Redemption Rate, Point Liability (total outstanding points × redemption value), Tier Attainment Distribution, and Program ROI. CRM Analytics Loyalty apps provide pre-built dashboards for program performance, member engagement, and financial liability. Member 360 views surface all loyalty activity alongside CRM data. Churn prediction identifies at-risk members for proactive re-engagement. Cohort analysis tracks how engagement changes as members progress through tiers. The exam tests which CRM Analytics datasets are populated by Loyalty data, how to measure point liability from journal records, and how to configure a member churn alert.'),
  ]),

  'manufacturing-cloud-ap': kc_block('Manufacturing Cloud AP: Key Concepts for the Exam', [
    ('Account-Based Forecasting & Sales Agreements',
     'Manufacturing Cloud centers on the Sales Agreement object — a negotiated contract between a manufacturer and a distributor/dealer defining expected purchase volumes and prices over a period. Sales Agreement Terms define the monthly or quarterly expected volumes and net price for each product. Actuals (from Orders or Opportunities) are compared against agreement terms to show attainment. Account Forecasts roll up agreement actuals, open opportunities, and planned volumes into a single account-level demand forecast. Forecast Adjustments allow sales managers to manually override system-generated forecasts. The AP exam tests how Sales Agreements feed Account Forecasts, how actuals are calculated from order data, and how to configure forecast windows and adjustment permissions.'),
    ('Run Rate Business & Demand Planning',
     'Run Rate Business tracks recurring purchase patterns from existing customers who order the same products regularly without a formal sales agreement. Manufacturing Cloud captures this demand by analyzing historical order data and projecting forward consumption. Run Rate Accounts have predictable demand signals that feed into the aggregate forecast. Demand Planning integration connects Manufacturing Cloud forecasts to ERP or S&OP (Sales & Operations Planning) systems. Forecast Collaboration allows multiple stakeholders (sales, supply chain, finance) to view and adjust the forecast. The exam tests how run rate demand is captured, how it differs from agreement-based demand, and how combined forecasts are presented to stakeholders.'),
    ('Partner Visit Management & Field Execution',
     'Manufacturing Cloud includes Partner Visit Management for field teams that visit dealer and distributor accounts. Visit Plans define visit schedules and objectives. During visits, reps review agreement attainment, discuss upcoming orders, capture competitive intelligence, and update account plans. Action Plans define repeatable activity checklists for common visit scenarios. Assessments capture structured data during visits (dealer satisfaction surveys, inventory counts). Mobile access via the Salesforce app enables reps to complete visit activities offline. The exam tests how to configure a visit plan, associate action plan templates, and surface agreement attainment data on the account page for use during dealer visits.'),
    ('Pricing, Rebates & Incentive Management',
     'Rebate Management in Manufacturing Cloud handles volume-based, growth-based, and promotional rebates paid to distributors and dealers. Rebate Programs define the qualification criteria and payout rates. Rebate Tiers apply higher payout rates at higher volume thresholds. Accruals track the estimated rebate liability as transactions occur. Payouts settle the final rebate amount at the end of the program period. Price Books and contract-level pricing (Negotiated Pricing) define the net price terms in Sales Agreements. The AP exam tests how to configure a tiered rebate program, how accruals are calculated from sales data, and how payouts are processed at program end.'),
    ('Integration with ERP & Supply Chain',
     'Manufacturing Cloud integrates with ERP systems (SAP, Oracle, Infor) to exchange order data, inventory levels, and financial actuals. MuleSoft is commonly used as the integration middleware for real-time or batch data exchange. Order data from ERP feeds the Sales Agreement attainment calculation. Inventory levels from ERP support demand planning accuracy. Product pricing maintained in ERP is synced to Salesforce Price Books. The AP exam tests the integration architecture for a Manufacturing Cloud + SAP scenario — which data flows in each direction, how to handle data transformation differences, and how to design for resiliency when the ERP is temporarily unavailable.'),
  ]),

  'mulesoft-integration-foundations': kc_block('MuleSoft Integration Foundations: Key Concepts for the Exam', [
    ('API-Led Connectivity & Anypoint Platform',
     'MuleSoft&apos;s API-led connectivity organizes integrations into three reusable layers: System APIs (connect directly to backend systems — SAP, Salesforce, databases), Process APIs (orchestrate business logic across multiple systems — order processing, customer onboarding), and Experience APIs (tailored for consuming clients — mobile app, web portal, partner). This layered approach promotes reusability — change a System API once and all Process APIs that use it automatically benefit. Anypoint Platform is the unified development and management environment: Anypoint Studio (IDE), Design Center (API design), Exchange (reuse hub), Runtime Manager (deployment), API Manager (governance). The exam tests which API layer handles a given integration scenario.'),
    ('Mule 4 Flows & Core Concepts',
     'A Mule 4 application consists of Flows triggered by a Source (HTTP listener, Salesforce trigger, scheduler) and processed by a sequence of Components (transformers, connectors, routers, error handlers). The Mule Event contains a Message (payload + attributes) and Variables. DataWeave 2.0 is the transformation language — `%dw 2.0` scripts transform data between formats (JSON, XML, CSV, Java). Connectors provide pre-built integration with systems: Salesforce Connector, HTTP Connector, Database Connector, Anypoint MQ. Error Handling: Try scope, On Error Continue, On Error Propagate define how errors are caught and handled. The exam tests basic flow design, DataWeave syntax, and error handling patterns.'),
    ('DataWeave Transformations',
     'DataWeave is MuleSoft&apos;s functional transformation language. Key syntax: `payload` accesses the incoming message body; `.` navigates object fields; `map` transforms arrays; `filter` selects elements; `pluck` converts objects to arrays; `reduce` aggregates; `if/else` handles conditionals. Type coercion converts between data types. Output directives specify the target format: `output application/json`, `output application/xml`. DataWeave modules provide utility functions (strings, dates, crypto). Mapping JSON to XML or flattening nested structures are common exam tasks. The Integration Foundations exam tests reading and writing basic DataWeave scripts for field mapping, conditional logic, and array transformation.'),
    ('Connectors & Integration Patterns',
     'Common MuleSoft connectors tested in Foundations: HTTP (REST API calls), Salesforce (CRUD, bulk, streaming), Database (SQL queries, stored procs), Anypoint MQ (async messaging), Scheduler (time-based triggers), File (read/write), SMTP (email). Integration patterns: Request-Reply (synchronous REST), Publish-Subscribe (Platform Events, Anypoint MQ topics), Batch Processing (large volume data loads), Polling (scheduled data sync). API-led connectivity promotes the Pub/Sub pattern for decoupling producers and consumers. The exam tests which connector and pattern to apply for a given scenario — synchronous vs. asynchronous, real-time vs. batch, point-to-point vs. hub-and-spoke.'),
    ('Deployment & API Management Basics',
     'MuleSoft applications deploy to Anypoint Runtime: CloudHub (Salesforce-managed cloud), Runtime Fabric (customer-managed Kubernetes), or On-Premises. CloudHub workers are the compute units — size by memory and vCores. Anypoint API Manager applies policies to APIs: rate limiting, OAuth 2.0 authentication, IP allowlisting, SLA tiers. API Autodiscovery links a deployed Mule app to an API Manager policy. Exchange hosts reusable assets: API specifications (RAML/OAS), connectors, templates, and examples. The Foundations exam tests the deployment options, how to apply an OAuth policy via API Manager, and how to publish a reusable asset to Anypoint Exchange.'),
  ]),
}

def insert_key_concepts(slug, kc_html):
    path = os.path.join(BASE, slug, 'page.tsx')
    if not os.path.exists(path):
        print(f"SKIP (not found): {slug}")
        return
    content = open(path, encoding='utf-8').read()
    if 'id="key-concepts"' in content:
        print(f"SKIP (already has KCs): {slug}")
        return
    target = '          <div id="practice-questions"'
    if target not in content:
        target = '            <div id="practice-questions"'
    if target not in content:
        print(f"WARN: could not find practice-questions div in {slug}")
        return
    content = content.replace(target, kc_html + target, 1)
    content = re.sub(
        r"(\{ id: 'practice-questions', title: '[^']+' \})",
        "{ id: 'key-concepts', title: 'Key Concepts' },\n              \\1",
        content, count=1
    )
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  OK: {slug}")

print("Batch 2: processing pages...")
for slug, html in PAGES.items():
    insert_key_concepts(slug, html)
print("Done.")
