#!/usr/bin/env python3
"""
Extract "3 Concepts" section from each exam-tips page and generate
concept FAQ entries (one Q&A per concept) for src/lib/exam-tips-concept-faqs.ts.

Usage: python3 scripts/extract-concept-faqs.py
Reads: src/app/*/page.tsx (exam-tips pages)
Outputs: TS snippet to stdout (merge into exam-tips-concept-faqs.ts)
"""

import re
from pathlib import Path

APP = Path(__file__).resolve().parent.parent / "src" / "app"
# Match exam-tips page directories
PAGE_DIRS = sorted(d for d in APP.iterdir() if d.is_dir() and "exam-tips" in d.name and (d / "page.tsx").exists())


def extract_concepts(content: str) -> list[tuple[str, str]] | None:
    """Extract 3 concept (title, body) pairs from the amber '3 Concepts' section. Returns None if not found."""
    if "3 Concepts That Fail Most" not in content:
        return None
    # Find the amber section and the block with space-y-5
    section = re.search(
        r'border-amber-100[^>]*>[\s\S]*?<div className="space-y-5">\s*([\s\S]*?)\s*</div>\s*</section>',
        content,
        re.DOTALL,
    )
    if not section:
        return None
    block = section.group(1)
    # Each concept: <div> ... <p className="font-semibold ...">1. Title</p> ... <p className="text-sm text-gray-700">body</p>
    pattern = re.compile(
        r'<p className="font-semibold[^"]*">\s*\d+\.\s*([^<]+)</p>\s*<p className="text-sm text-gray-700">\s*([\s\S]*?)\s*</p>',
        re.DOTALL,
    )
    matches = pattern.findall(block)
    if len(matches) < 3:
        return None
    out = []
    for title, body in matches[:3]:
        title = re.sub(r"\s*—\s*.*$", "", title).strip()
        title = title.strip()
        body = (
            body.replace("&apos;", "'")
            .replace("&amp;", "&")
            .replace("&quot;", '"')
            .replace("&ldquo;", '"')
            .replace("&rdquo;", '"')
            .replace("\n", " ")
        )
        body = re.sub(r"\s+", " ", body).strip()
        if len(body) > 400:
            body = body[:397] + "..."
        out.append((title, body))
    return out


def slug_from_path(p: Path) -> str:
    return p.name  # e.g. adm-201-exam-tips-2026


def exam_name_from_slug(slug: str) -> str:
    """Derive exam name for FAQ question, e.g. ADM-201, App Builder, PD2."""
    m = re.match(r"adm-201-exam-tips", slug)
    if m:
        return "ADM-201"
    if slug == "app-builder-exam-tips":
        return "App Builder"
    if slug == "pd1-exam-tips-2026":
        return "PD1"
    if slug == "pd2-exam-tips-2026":
        return "PD2"
    if slug == "advanced-administrator-exam-tips":
        return "Advanced Administrator"
    if slug == "service-cloud-consultant-exam-tips":
        return "Service Cloud Consultant"
    if slug == "sales-cloud-exam-tips":
        return "Sales Cloud Consultant"
    # Generic: capitalize first letter of each word, e.g. "data-cloud-consultant" -> "Data Cloud Consultant"
    return slug.replace("-exam-tips-2026", "").replace("-exam-tips", "").replace("-", " ").title()


def main():
    entries = []
    for page_dir in PAGE_DIRS:
        page_file = page_dir / "page.tsx"
        content = page_file.read_text()
        concepts = extract_concepts(content)
        slug = slug_from_path(page_dir)
        if not concepts:
            continue
        exam_name = exam_name_from_slug(slug)
        faqs = []
        for title, body in concepts:
            # Short topic for question: first 50 chars of title or up to "—"
            topic = title.split("—")[0].strip() if "—" in title else title
            if len(topic) > 55:
                topic = topic[:52] + "..."
            q = f"Why do most {exam_name} candidates fail questions about {topic}?"
            # Escape single quotes in body for TS string
            body_esc = body.replace("\\", "\\\\").replace("'", "\\'")
            faqs.append((q, body_esc))
        entries.append((slug, faqs))

    # Output TypeScript
    print("// Generated by scripts/extract-concept-faqs.py — concept FAQs for exam tips pages")
    print("export interface ConceptFaq { question: string; answer: string }")
    print("")
    print("const CONCEPT_FAQS: Record<string, ConceptFaq[]> = {")
    for slug, faqs in entries:
        print(f"  '{slug}': [")
        for q, a in faqs:
            print(f"    {{ question: '{q.replace(chr(39), chr(92)+chr(39))}', answer: '{a}' }},")
        print("  ],")
    print("};")
    print("")
    print("export function getConceptFaqs(pageSlug: string): ConceptFaq[] {")
    print("  return CONCEPT_FAQS[pageSlug] ?? [];")
    print("}")


if __name__ == "__main__":
    main()
